/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: day40.c                                               *
* Font:        »ªÎÄÁ¥Êé                                              *
* Height:      40                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  40                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\1.txt            *
*                                                                    *
**********************************************************************
*/

#include "CUIGUI_FONT.H"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontday40;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontday40_5929[200] = { /* code 5929 */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,XXXXX___,___X____,________,________,
  ______XX,XX______,__XXX___,________,________,
  ________,________,__XXX___,________,________,
  ________,________,XXXXXXXX,XXXXXXXX,X_______,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,XXXXXX__,_______X,________,
  ______XX,XXXXX___,_XXXXX__,________,________,
  _______X,XX______,_XXXXXX_,________,________,
  ________,________,_XXXXXXX,________,________,
  ________,________,XXX__XXX,________,________,
  ________,_______X,XX____XX,X_______,________,
  ________,_______X,XX____XX,XX______,________,
  ________,______XX,X______X,XXX_____,________,
  ________,____XXXX,________,XXXXX___,________,
  ____XX__,__XXXXX_,________,XXXXXXXX,________,
  ____XXXX,XXXXXX__,________,_XXXXXXX,XXX_____,
  ____XXXX,XXXXX___,________,_XXXXXXX,XXXXXX__,
  ____XXXX,XXX_____,________,__XXXXXX,XXXXX___,
  ____XXXX,X_______,________,___XXXXX,XXXX____,
  ____XXX_,________,________,____XXXX,XXX_____,
  ________,________,________,______XX,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontday40_65B0[200] = { /* code 65B0 */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,____XXX_,________,________,________,
  ________,____XXXX,________,___XXXXX,XXX_____,
  ________,___XXXXX,X_____XX,XXXXXXXX,XXX_____,
  _______X,XXXXXXXX,XXXXX_XX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXX___X,XXXXX_XX,XXXXXXXX,________,
  ___XXXXX,XXX____X,XX____XX,X_______,________,
  ________,_XX____X,XX____XX,________,________,
  ________,_XXXXXXX,X_____XX,________,______X_,
  _____XXX,XXXXXXXX,XXX___XX,XXXXXXXX,XXXXXX__,
  ____XXXX,XXXXXXXX,XXX___XX,XXXXXXXX,XXXXXX__,
  ____XXXX,X___XXX_,______XX,XXXXXXXX,XXXXX___,
  ________,____XX__,______XX,XXXXXXXX,XXXX____,
  ________,__XXXXXX,XXX___XX,XX__XXXX,XXX_____,
  _______X,XXXXXXXX,XXX___XX,X____XXX,________,
  _____XXX,XXXXXXXX,XXX___XX,_____XXX,________,
  ___XXXXX,XXXXXXX_,______XX,_____XXX,________,
  ___XXXXX,X___XX__,______XX,_____XXX,________,
  ___XXX__,____XX__,XXXX__XX,_____XXX,________,
  ________,_X__XX__,XXX__XXX,_____XXX,________,
  _______X,XX__XX__,_XX__XXX,_____XXX,________,
  ___XXXXX,XX__XX__,_____XXX,_____XXX,________,
  ____XXXX,X___XX__,____XXXX,_____XXX,________,
  ____XXXX,____XX__,___XXXX_,_____XXX,________,
  ________,____XX__,__XXXXX_,_____XXX,________,
  ________,____XX__,____X___,_____XXX,________,
  ________,________,________,_____XXX,________,
  ________,________,________,_____X__,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontday40_6709[200] = { /* code 6709 */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,__XX____,________,________,
  ________,________,_XXXX___,________,________,
  ____X___,_XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ____XXXX,XXXX___X,XXXX____,____XXXX,XXXXXX__,
  ____XXXX,_______X,XXX_____,_______X,XXXXX___,
  ________,______XX,XXXXXXXX,XXXXXX__,_XXX____,
  ________,_____XXX,XXXXXXXX,XXXXXXX_,________,
  ________,____XXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XX______,___XXX__,________,
  ________,XXXXXX_X,XX______,___XXX__,________,
  ___XXXXX,XXXXX__X,XXXXXXXX,XXXXX___,________,
  ___XXXXX,XXXX___X,XXXXXXXX,XXXXX___,________,
  ___XXXXX,XX_____X,XXXXXXXX,XXXXX___,________,
  ___XXXXX,X______X,XX______,___XX___,________,
  ____XXX_,_______X,X_______,___XX___,________,
  ____X___,______XX,XXXXXXXX,XXXXX___,________,
  ________,______XX,XXXXXXXX,XXXXX___,________,
  ________,______XX,XXXXXXXX,XXXXX___,________,
  ________,_____XXX,XX______,___XX___,________,
  ________,_____XXX,________,___XX___,________,
  ________,____XXXX,________,___XX___,________,
  ________,__XXXXX_,________,___XX___,________,
  ________,_XXXXXX_,________,___XX___,________,
  _______X,XXXXXX__,________,___XX___,________,
  _______X,XXX_____,________,____X___,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontday40_6BCF[200] = { /* code 6BCF */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,_____XX_,________,________,________,
  ________,_____XX_,________,________,________,
  ________,___XXXXX,________,________,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXX___,________,________,________,
  ______XX,XXX_____,________,________,________,
  ________,________,________,________,________,
  ________,________,XXXXXXXX,XXXXX___,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,___XXXX_,___XX___,____XXXX,________,
  ________,____XX__,___XX___,____XXX_,________,
  ________,___XX___,_XXXX___,____XX__,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXX_,______X_,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXX___,_XXX____,XXXXXXXX,XXXXX___,
  __XXX___,XXX_____,__XX____,__XX_XXX,XXXX____,
  ________,XXX_____,__XX____,__X_____,XXX_____,
  _______X,XX____XX,XXXX____,_XX_____,________,
  _____XXX,XXXXXXXX,XXXX____,_XX_____,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,________,______XX,XXXXXXXX,XXX_____,
  ________,________,_______X,XXXXXXXX,XX______,
  ________,________,______XX,X_____X_,________,
  ________,________,_____XXX,________,________,
  ________,_____XXX,XXXXXXXX,________,________,
  ________,________,XXXXXXX_,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontday40_88C5[200] = { /* code 88C5 */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,X_______,__X_____,________,
  _______X,_______X,XX______,__XX____,________,
  _______X,XXX____X,XX______,XXXXXXXX,________,
  ______XX,XXXXXXXX,XX_XXXXX,XXXXXXXX,XXX_____,
  ______XX,XXXXXXXX,X__XXXXX,XXXXXXXX,XXX_____,
  _______X,XXXXX__X,X___XXXX,_XX_____,________,
  ________,_______X,X_______,_XX_____,________,
  ________,____XX_X,X_______,_XXXXXXX,________,
  ________,_XXXX__X,X_____XX,XXXXXXXX,XX______,
  ______XX,XXXX___X,X__XXXXX,XXXXXXXX,X_______,
  ______XX,XXXX__XX,X__XXX__,________,________,
  ______XX,XX____XX,X___XX__,________,________,
  ________,______XX,____XXXX,XXXXXXXX,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,XXXXXXXX,XX____XX,X_______,________,
  ________,XXXXXXXX,X_____XX,X_______,________,
  ________,XXX___XX,_____XXX,XX______,________,
  ________,_____XXX,____XXXX,XXX_____,________,
  ________,____XXX_,___XX___,XXXX____,________,
  ________,__XXXXX_,_XXX____,_XXXX___,________,
  ___X____,_XXXXXX_,________,_XXXXX__,________,
  ___XXXXX,XXX__XX_,______XX,XXXXXXXX,________,
  ___XXXXX,XX___XX_,__XXXXXX,XX_XXXXX,XX______,
  ___XXXXX,X____XXX,XXXXXXXX,XX__XXXX,XXXX____,
  ____XXX_,____XXXX,XXXXXXXX,X____XXX,XXXXXXX_,
  ________,____XXXX,XXXXXX__,______XX,XXXXXX__,
  ________,____XXX_,________,_______X,XXXX____,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontday40_903C[200] = { /* code 903C */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,XXX_____,________,
  _______X,XX______,___XXXXX,XXXXXXXX,XX______,
  ______XX,XXXXX___,XXXXXXXX,XXXXXXXX,X_______,
  ______XX,XXXXX___,XXXXX___,________,________,
  ________,XX______,_____XXX,XXXXXX_X,X_______,
  ________,________,XXXXXXXX,XXXXXXXX,X_______,
  ________,________,_XXXXX__,______XX,________,
  ______XX,XXXXX___,_XXX____,_____XX_,________,
  ______XX,XXXX____,_XX__XXX,XXXXXX__,________,
  ______XX,XX______,_XXXXXXX,XXXXX___,________,
  ________,________,_XXXXX__,________,________,
  ________,________,______XX,XXXXXXXX,XX______,
  ________,_XXX____,__XXXXXX,XXXXXXXX,X_______,
  ______XX,XXXX____,XXXX___X,X______X,X_______,
  ______XX,XXX_____,XX____XX,XX__X_XX,________,
  ______XX,X_______,XXXXXXXX,XXXXXXXX,________,
  ________,________,XXXXXXXX,XXXXXXXX,________,
  ________,_XX_____,XXXX__XX,X_____X_,________,
  ________,XXX____X,X_____XX,X____XX_,________,
  ______XX,XX_____X,X_XXXXXX,XXXXXX__,________,
  _____XXX,X_____XX,XXXXXXXX,XXXXXX__,________,
  ____XXXX,XXXXXXXX,XXXX____,________,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,_____X__,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,XXXXX___,
  ________,________,___XXXXX,XXXXXXXX,XXXXX___,
  ________,________,______XX,XXXXXXXX,XXXX____,
  ________,________,________,_XXXXXXX,XXX_____,
  ________,________,________,____XXXX,XX______,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontday40_90FD[200] = { /* code 90FD */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,_____XX_,________,________,________,
  ________,____XXXX,________,________,________,
  ________,_XXXXXXX,XXXXXXX_,XXXXXXXX,XXX_____,
  ____XXXX,XXXXXXXX,XXXXXXX_,XXXXXXXX,XXXXXX__,
  ____XXXX,XXXXXXXX,XXXXX__X,XXXXXXXX,XXXXX___,
  ____XXXX,_____XX_,__X_____,XXXX___X,XXXX____,
  ________,____XXXX,XXXXX___,XX____XX,XX______,
  ________,XXXXXXXX,XXXXXXX_,XX___XXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXX__,XX_XXXX_,________,
  ____XXXX,XXXXXXXX,________,XXXXXX__,________,
  ____XXXX,X__XXX__,________,XXXXXXX_,________,
  ____XX__,__XXX__X,XXXXX___,XXXXXXXX,XX______,
  ________,_XXXXXXX,XXXXX___,XXX___XX,XXX_____,
  _______X,XXXXX___,___XX___,XXX_____,XXXXX___,
  ______XX,XXX_____,__XX____,XXX_____,XXXXX___,
  _____XXX,__X__XXX,XXXX____,XXX___XX,XXXXX___,
  ____XXX_,__XXXXXX,XXXX____,XXXXXXXX,XX______,
  ____XX__,__XXXX__,__XX____,XXXXXXXX,________,
  ________,_XXX____,__XX____,XXXXX___,________,
  ________,_XX____X,XXXX____,XXX_____,________,
  ________,_XXXXXXX,XXXX____,XXX_____,________,
  ________,_XXXXXXX,XXXX____,XXX_____,________,
  ________,_XXXX___,_______X,XXX_____,________,
  ________,_X______,_______X,XXX_____,________,
  ________,________,_______X,XX______,________,
  ________,________,_______X,XX______,________,
  ________,________,________,X_______,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontday40_CharInfo[7] = {
   {  40,  40,  5, acGUI_Fontday40_5929 } /* code 5929 */
  ,{  40,  40,  5, acGUI_Fontday40_65B0 } /* code 65B0 */
  ,{  40,  40,  5, acGUI_Fontday40_6709 } /* code 6709 */
  ,{  40,  40,  5, acGUI_Fontday40_6BCF } /* code 6BCF */
  ,{  40,  40,  5, acGUI_Fontday40_88C5 } /* code 88C5 */
  ,{  40,  40,  5, acGUI_Fontday40_903C } /* code 903C */
  ,{  40,  40,  5, acGUI_Fontday40_90FD } /* code 90FD */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontday40_Prop7 = {
   0x90FD /* first character */
  ,0x90FD /* last character  */
  ,&GUI_Fontday40_CharInfo[  6] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontday40_Prop6 = {
   0x903C /* first character */
  ,0x903C /* last character  */
  ,&GUI_Fontday40_CharInfo[  5] /* address of first character */
  ,&GUI_Fontday40_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontday40_Prop5 = {
   0x88C5 /* first character */
  ,0x88C5 /* last character  */
  ,&GUI_Fontday40_CharInfo[  4] /* address of first character */
  ,&GUI_Fontday40_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontday40_Prop4 = {
   0x6BCF /* first character */
  ,0x6BCF /* last character  */
  ,&GUI_Fontday40_CharInfo[  3] /* address of first character */
  ,&GUI_Fontday40_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontday40_Prop3 = {
   0x6709 /* first character */
  ,0x6709 /* last character  */
  ,&GUI_Fontday40_CharInfo[  2] /* address of first character */
  ,&GUI_Fontday40_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontday40_Prop2 = {
   0x65B0 /* first character */
  ,0x65B0 /* last character  */
  ,&GUI_Fontday40_CharInfo[  1] /* address of first character */
  ,&GUI_Fontday40_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontday40_Prop1 = {
   0x5929 /* first character */
  ,0x5929 /* last character  */
  ,&GUI_Fontday40_CharInfo[  0] /* address of first character */
  ,&GUI_Fontday40_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontday40 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,40 /* height of font  */
  ,40 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontday40_Prop1}
  ,31 /* Baseline */
  ,17 /* Height of lowercase characters */
  ,25 /* Height of capital characters */
};

