/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: huawen16.c                                            *
* Font:        »ªÎÄ¿¬Ìå                                              *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\11.txt           *
* Character enabled:   0x20 (32)                                     *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\11.txt           *
*                                                                    *
**********************************************************************
*/

#include "CUIGUI_FONT.H"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fonthuawen16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_0020[ 16] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ___X____,
  __XX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXX___,
  _X__X___,
  ____X___,
  ____X___,
  __XXXX__,
  _____X__,
  _____X__,
  _____X__,
  _XXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  ____X___,
  ____X___,
  ___XX___,
  __X_X___,
  _X__X___,
  _X__X___,
  XXXXXX__,
  ____X___,
  ____X___,
  ____X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  __XXXX__,
  __X_____,
  __X_____,
  __X_____,
  __XXXX__,
  ______X_,
  ______X_,
  ______X_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ____XX__,
  ___X____,
  __X_____,
  __X_____,
  _X_XX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXX__,
  _____X__,
  ____X___,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _XX_X___,
  ___XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XX_X__,
  ____X___,
  ____X___,
  ___X____,
  _XX_____,
  ________,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_514B[ 32] = { /* code 514B */
  ________,________,
  ________,________,
  _______X,________,
  _______X,________,
  _____XXX,X_______,
  ______X_,________,
  ______XX,XX______,
  ____XX__,_X______,
  ____X___,X_______,
  _____XXX,________,
  _____X_X,________,
  ____X__X,________,
  __XX___X,____X___,
  _X______,XXXXX___,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_5766[ 32] = { /* code 5766 */
  ________,________,
  ________,________,
  ___X____,________,
  ____X___,________,
  ____X___,XXXX____,
  ____X__X,___X____,
  ____XXXX,XX_X____,
  ___XX__X,__X_____,
  ____X__X,XXX_____,
  ____XXX_,________,
  ___XX___,________,
  __X____X,XXXXX___,
  _____XX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_5927[ 32] = { /* code 5927 */
  ________,________,
  ________,________,
  ______XX,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,XXXX____,
  ____XXXX,________,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__XXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_6218[ 32] = { /* code 6218 */
  ________,________,
  ________,________,
  _______X,________,
  _______X,_XX_____,
  ____X___,X_______,
  ____X___,X_______,
  ____XXX_,XXX_____,
  ____X__X,X_X_____,
  __XXXXX_,X_X_____,
  __X__XX_,_X______,
  __X__X__,XX______,
  ___XX_XX,__X_____,
  ________,___XX___,
  ________,____XX__,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_6280[ 32] = { /* code 6280 */
  ________,________,
  ________,________,
  ____X___,XX______,
  ____X___,X_______,
  ____X___,X_______,
  ___XXXXX,XXX_____,
  ____X___,X_______,
  ____XX_X,XXX_____,
  ___XX_X_,_X______,
  _XX_X__X,_X______,
  ____X___,X_______,
  ____X_XX,_XX_____,
  ___XXX__,__XXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_63A2[ 32] = { /* code 63A2 */
  ________,________,
  ________,________,
  ____X___,________,
  ____X___,_XXX____,
  ____X_XX,XX_XX___,
  ___XXXXX,__X_____,
  ____X_X_,X_______,
  ____XX__,XXXX____,
  ___XXXXX,X_______,
  _XX_X__X,XX______,
  ____X_X_,X_X_____,
  ____XX__,X__XX___,
  ___XX___,X_______,
  ________,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_79D1[ 32] = { /* code 79D1 */
  ________,________,
  ________,________,
  ________,__X_____,
  _____XX_,__X_____,
  ___XX___,X_X_____,
  ____X___,__X_____,
  ___XXX__,X_X_____,
  _XX_XX__,__XXXX__,
  ___XX_XX,XXX_____,
  __X_X___,__X_____,
  _X__X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ________,__X_____,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen16_957F[ 32] = { /* code 957F */
  ________,________,
  ________,________,
  _____X__,_X______,
  _____X__,XX______,
  _____X_X,X_______,
  _____XX_,________,
  _____X_X,XXXX____,
  __XXXXX_,________,
  _____X_X,________,
  _____X__,X_______,
  _____X__,_XX_____,
  _____XX_,__XXXX__,
  ____XX__,________,
  ____X___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fonthuawen16_CharInfo[18] = {
   {   4,   4,  1, acGUI_Fonthuawen16_0020 } /* code 0020 */
  ,{   7,   7,  1, acGUI_Fonthuawen16_0031 } /* code 0031 */
  ,{   7,   7,  1, acGUI_Fonthuawen16_0032 } /* code 0032 */
  ,{   7,   7,  1, acGUI_Fonthuawen16_0033 } /* code 0033 */
  ,{   7,   7,  1, acGUI_Fonthuawen16_0034 } /* code 0034 */
  ,{   7,   7,  1, acGUI_Fonthuawen16_0035 } /* code 0035 */
  ,{   7,   7,  1, acGUI_Fonthuawen16_0036 } /* code 0036 */
  ,{   7,   7,  1, acGUI_Fonthuawen16_0037 } /* code 0037 */
  ,{   7,   7,  1, acGUI_Fonthuawen16_0038 } /* code 0038 */
  ,{   7,   7,  1, acGUI_Fonthuawen16_0039 } /* code 0039 */
  ,{  14,  14,  2, acGUI_Fonthuawen16_514B } /* code 514B */
  ,{  14,  14,  2, acGUI_Fonthuawen16_5766 } /* code 5766 */
  ,{  14,  14,  2, acGUI_Fonthuawen16_5927 } /* code 5927 */
  ,{  14,  14,  2, acGUI_Fonthuawen16_6218 } /* code 6218 */
  ,{  14,  14,  2, acGUI_Fonthuawen16_6280 } /* code 6280 */
  ,{  14,  14,  2, acGUI_Fonthuawen16_63A2 } /* code 63A2 */
  ,{  14,  14,  2, acGUI_Fonthuawen16_79D1 } /* code 79D1 */
  ,{  14,  14,  2, acGUI_Fonthuawen16_957F } /* code 957F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen16_Prop10 = {
   0x957F /* first character */
  ,0x957F /* last character  */
  ,&GUI_Fonthuawen16_CharInfo[ 17] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen16_Prop9 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_Fonthuawen16_CharInfo[ 16] /* address of first character */
  ,&GUI_Fonthuawen16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen16_Prop8 = {
   0x63A2 /* first character */
  ,0x63A2 /* last character  */
  ,&GUI_Fonthuawen16_CharInfo[ 15] /* address of first character */
  ,&GUI_Fonthuawen16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen16_Prop7 = {
   0x6280 /* first character */
  ,0x6280 /* last character  */
  ,&GUI_Fonthuawen16_CharInfo[ 14] /* address of first character */
  ,&GUI_Fonthuawen16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen16_Prop6 = {
   0x6218 /* first character */
  ,0x6218 /* last character  */
  ,&GUI_Fonthuawen16_CharInfo[ 13] /* address of first character */
  ,&GUI_Fonthuawen16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen16_Prop5 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Fonthuawen16_CharInfo[ 12] /* address of first character */
  ,&GUI_Fonthuawen16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen16_Prop4 = {
   0x5766 /* first character */
  ,0x5766 /* last character  */
  ,&GUI_Fonthuawen16_CharInfo[ 11] /* address of first character */
  ,&GUI_Fonthuawen16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen16_Prop3 = {
   0x514B /* first character */
  ,0x514B /* last character  */
  ,&GUI_Fonthuawen16_CharInfo[ 10] /* address of first character */
  ,&GUI_Fonthuawen16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen16_Prop2 = {
   0x0031 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_Fonthuawen16_CharInfo[  1] /* address of first character */
  ,&GUI_Fonthuawen16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen16_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_Fonthuawen16_CharInfo[  0] /* address of first character */
  ,&GUI_Fonthuawen16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fonthuawen16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fonthuawen16_Prop1}
  ,12 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

