/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: huawen12.c                                            *
* Font:        »ªÎÄ¿¬Ìå                                              *
* Height:      12                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  12                                           *
* Read pattern file: C:\Users\Administrator\Desktop\111.txt          *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\111.txt          *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fonthuawen12;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_4E2D[ 24] = { /* code 4E2D */
  ________,________,
  _____X__,________,
  _____X__,________,
  __XXXXXX,XX______,
  __X__X__,X_______,
  ___XXXXX,X_______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_4E9A[ 24] = { /* code 4E9A */
  ________,________,
  ________,________,
  _______X,X_______,
  __XXXXX_,________,
  ____X_X_,X_______,
  __X_X_X_,X_______,
  ___XX_XX,________,
  ____X_XX,X_______,
  _XXX_X__,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_4EBA[ 24] = { /* code 4EBA */
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ____XX__,________,
  ____X_X_,________,
  ___X___X,________,
  __X_____,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_51C0[ 24] = { /* code 51C0 */
  ________,________,
  ______X_,________,
  _____XXX,X_______,
  ____X__X,________,
  ______XX,X_______,
  ___XXXXX,XXX_____,
  __X___X_,X_______,
  _X_XXXXX,X_______,
  ______X_,________,
  ______X_,________,
  _____X__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_51CF[ 24] = { /* code 51CF */
  ________,________,
  ______X_,________,
  ______X_,________,
  __X____X,________,
  ____XXXX,________,
  ____XX_X,_X______,
  __X_XXXX,X_______,
  _X__XXX_,X_______,
  ___X___X,X_______,
  ___X____,_XX_____,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_5206[ 24] = { /* code 5206 */
  ________,________,
  _____X__,________,
  ______X_,________,
  ____X__X,________,
  ___X____,X_______,
  __X__XXX,_XX_____,
  ___XX__X,________,
  ____X__X,________,
  ___X__X_,________,
  __X__XX_,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_521D[ 24] = { /* code 521D */
  ________,________,
  ___X____,________,
  ____X___,________,
  ____X___,XX______,
  _XXXXXXX,_X______,
  ___X_X_X,_X______,
  __XXX_X_,_X______,
  _X_X__X_,_X______,
  ___X_X__,X_______,
  ___XX___,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_52A0[ 24] = { /* code 52A0 */
  ________,________,
  ________,________,
  ____X___,________,
  ___X____,________,
  ___XXXXX,XX______,
  __XX_XX_,_X______,
  ___X_XX_,X_______,
  __X__XXX,________,
  __X_X___,________,
  _X_XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_5316[ 24] = { /* code 5316 */
  ________,________,
  _____X__,________,
  ____XX__,X_______,
  ___X_X_X,________,
  __XX_XX_,________,
  _X_XXX__,________,
  ___X_X__,_X______,
  ___X_X__,_X______,
  ___X__XX,X_______,
  ___X____,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_533B[ 24] = { /* code 533B */
  ________,________,
  _______X,X_______,
  ___XXXX_,________,
  __X__X__,________,
  __X_XXX_,________,
  __X_XX_X,________,
  __XXXXX_,________,
  __X__X_X,________,
  __X_X___,________,
  __XXXXXX,XX______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_5668[ 24] = { /* code 5668 */
  ________,________,
  ______XX,X_______,
  __XXX_X_,X_______,
  __X_X__X,________,
  ___X_XXX,X_______,
  ___XXXX_,________,
  ____X_X_,________,
  __XXX__X,XXX_____,
  __X_X_XX,XX______,
  ___X__XX,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_589E[ 24] = { /* code 589E */
  ________,________,
  ________,X_______,
  ___X_X_X,________,
  ___X____,XX______,
  ___XXXXX,_X______,
  ___XX_X_,_X______,
  ___XXXXX,X_______,
  __XX_X__,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  ________,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_5B9A[ 24] = { /* code 5B9A */
  ________,________,
  _____X__,________,
  ______XX,X_______,
  ___XXX__,X_______,
  __X__XX_,________,
  _____X__,________,
  ___X_XXX,________,
  ___XXX__,________,
  __X__XX_,________,
  _X_____X,XXX_____,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_5C11[ 24] = { /* code 5C11 */
  ________,________,
  _____X__,________,
  _____X__,________,
  _____X__,XX______,
  _____X__,________,
  __X__X_X,________,
  ______X_,________,
  ______X_,________,
  _____X__,________,
  ___XX___,________,
  __X_____,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_5DDE[ 24] = { /* code 5DDE */
  ________,________,
  ________,X_______,
  ___X__X_,X_______,
  ___X__X_,X_______,
  __XXX_XX,X_______,
  __XX__X_,X_______,
  ___X__X_,X_______,
  ___X__X_,X_______,
  __X_____,X_______,
  _X______,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_5E74[ 24] = { /* code 5E74 */
  ________,________,
  ___XX___,________,
  ___XXXXX,________,
  __X__X__,________,
  _X_XXXXX,________,
  __X__X__,________,
  ___XXXXX,XX______,
  XXX__X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_6548[ 24] = { /* code 6548 */
  ________,________,
  _______X,________,
  ____X__X,________,
  _____X_X,________,
  __XXX_X_,XX______,
  ___X_XXX,________,
  __X_X_XX,________,
  ___X_X_X,________,
  ___XX_X_,________,
  __X___XX,________,
  _____X__,XX______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_65E5[ 24] = { /* code 65E5 */
  ________,________,
  ________,________,
  _______X,________,
  ____XXXX,________,
  ____X__X,________,
  ____XXXX,________,
  ____X__X,________,
  ____XXXX,________,
  ____X__X,________,
  _______X,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_65F6[ 24] = { /* code 65F6 */
  ________,________,
  _______X,________,
  _______X,________,
  __XXX_XX,XX______,
  __X_XX_X,________,
  __XXXX_X,________,
  __X_X_XX,________,
  __XXX__X,________,
  __X_XX_X,________,
  ______XX,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_6708[ 24] = { /* code 6708 */
  ________,________,
  ____XXXX,________,
  ____X__X,________,
  ____X__X,________,
  ____XXXX,________,
  ____XXXX,________,
  ___X___X,________,
  ___X___X,________,
  __X____X,________,
  ______XX,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_673A[ 24] = { /* code 673A */
  ________,________,
  ___X____,________,
  ___X____,________,
  ___XXXXX,X_______,
  _XXX_X_X,________,
  ___X_X_X,________,
  __XXXX_X,__X_____,
  _X_XX__X,__X_____,
  ___XX___,XXX_____,
  ___X____,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_6C11[ 24] = { /* code 6C11 */
  ________,________,
  _____XXX,________,
  __XXX_XX,________,
  ___XXXX_,________,
  ___X__X_,________,
  ___XXXXX,________,
  ___X___X,________,
  ___X_X_X,________,
  __XXX___,X_X_____,
  ________,_XX_____,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_6E05[ 24] = { /* code 6E05 */
  ______X_,________,
  ______X_,________,
  ___XXXXX,________,
  _____XXX,________,
  __X___XX,XXX_____,
  ___XXXXX,________,
  ___XXX_X,________,
  __X_XXXX,________,
  __X_X__X,________,
  __X_X__X,________,
  _______X,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_6EE4[ 24] = { /* code 6EE4 */
  ________,________,
  _____X__,________,
  __X__XX_,________,
  _____X_X,X_______,
  _X__XXX_,X_______,
  ____XXXX,X_______,
  ____X_XX,________,
  __X_X_X_,_X______,
  _X_X__XX,X_______,
  ___XX__X,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_786E[ 24] = { /* code 786E */
  ________,________,
  ____XXXX,________,
  __XX__X_,X_______,
  ___X_X_X,________,
  __XXXXXX,XX______,
  _XX_XX_X,_X______,
  X_XX_XXX,XX______,
  _____XXX,XX______,
  ____X__X,_X______,
  ____X__X,XX______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_79D2[ 24] = { /* code 79D2 */
  ________,________,
  _______X,________,
  ___XX__X,________,
  ___X___X,XX______,
  _XXXX__X,__X_____,
  ___X_X_X,X_______,
  __XXX___,X_______,
  _X_X___X,________,
  ___X___X,________,
  ___X_XX_,________,
  ____X___,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_7A7A[ 24] = { /* code 7A7A */
  ________,________,
  _____X__,________,
  _____XXX,X_______,
  __XXX___,XX______,
  ____X_X_,________,
  ____X__X,________,
  ___X____,________,
  ____XXX_,________,
  _____X__,________,
  ___XXXXX,XX______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_7EC4[ 24] = { /* code 7EC4 */
  ________,________,
  ___X____,________,
  ___XX___,________,
  __X_X__X,X_______,
  _XXX_XXX,X_______,
  __X___X_,X_______,
  __XX__XX,X_______,
  ____X_X_,X_______,
  __XX_XXX,XXX_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_7F6E[ 24] = { /* code 7F6E */
  ________,________,
  _______X,X_______,
  ___XXXX_,X_______,
  ___XXX_X,________,
  _____XXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  __XXXXXX,XX______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_83B1[ 24] = { /* code 83B1 */
  ________,________,
  ____X__X,________,
  ____XXXX,XX______,
  ___XXXX_,________,
  _____X__,________,
  ___X_XXX,X_______,
  __X_XXX_,________,
  ___X_X_X,________,
  __X__X__,XX______,
  _X___X__,________,
  _____X__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_8BBE[ 24] = { /* code 8BBE */
  ________,________,
  ________,________,
  ___X_XXX,________,
  _____X_X,XX______,
  ___X_X__,________,
  _XXX_XXX,________,
  ___X_X_X,________,
  __X_X_X_,________,
  ___X__XX,________,
  __X_XX__,XXX_____,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_8C03[ 24] = { /* code 8C03 */
  ________,________,
  ___X____,XX______,
  ___X_XXX,_X______,
  ___X_XXX,XX______,
  _XXX_X_X,XX______,
  ___X_XXX,XX______,
  ___XXXXX,XX______,
  ___X_X__,_X______,
  ____X___,_X______,
  ____X___,XX______,
  ___X____,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_8FC7[ 24] = { /* code 8FC7 */
  ________,________,
  _______X,________,
  ___X___X,________,
  ______XX,XX______,
  ___XXX_X,________,
  ___X_X_X,________,
  ___X___X,________,
  __XXX_XX,________,
  _____XX_,________,
  _______X,XXX_____,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_95F4[ 24] = { /* code 95F4 */
  ________,________,
  ________,________,
  ___X___X,X_______,
  __X_XXX_,X_______,
  __X_X_X_,X_______,
  __X_XXX_,X_______,
  __X_X_X_,X_______,
  __X_XXX_,X_______,
  __X_____,X_______,
  ________,X_______,
  _______X,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_9662[ 24] = { /* code 9662 */
  ________,________,
  ______X_,________,
  __XX____,________,
  __XX____,X_______,
  __XXXXXX,X_______,
  __XX____,________,
  __X___XX,X_______,
  __X__XX_,________,
  __X_X_X_,_X______,
  __XX__XX,XX______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_96F6[ 24] = { /* code 96F6 */
  ________,________,
  ____XXX_,________,
  _____XXX,XX______,
  __XXXX_X,_X______,
  __XX_XX_,________,
  ____XXX_,________,
  ____XX_X,________,
  __XX_XXX,XX______,
  _X__X_X_,________,
  _____X__,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthuawen12_9AD8[ 24] = { /* code 9AD8 */
  ________,________,
  _____X__,________,
  _____XXX,X_______,
  ___XX_X_,________,
  ____XXX_,________,
  __XXX_XX,XX______,
  __X_XXX_,_X______,
  __X_XXX_,_X______,
  __X_____,_X______,
  __X____X,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fonthuawen12_CharInfo[37] = {
   {  11,  11,  2, acGUI_Fonthuawen12_4E2D } /* code 4E2D */
  ,{  11,  11,  2, acGUI_Fonthuawen12_4E9A } /* code 4E9A */
  ,{  11,  11,  2, acGUI_Fonthuawen12_4EBA } /* code 4EBA */
  ,{  11,  11,  2, acGUI_Fonthuawen12_51C0 } /* code 51C0 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_51CF } /* code 51CF */
  ,{  11,  11,  2, acGUI_Fonthuawen12_5206 } /* code 5206 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_521D } /* code 521D */
  ,{  11,  11,  2, acGUI_Fonthuawen12_52A0 } /* code 52A0 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_5316 } /* code 5316 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_533B } /* code 533B */
  ,{  11,  11,  2, acGUI_Fonthuawen12_5668 } /* code 5668 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_589E } /* code 589E */
  ,{  11,  11,  2, acGUI_Fonthuawen12_5B9A } /* code 5B9A */
  ,{  11,  11,  2, acGUI_Fonthuawen12_5C11 } /* code 5C11 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_5DDE } /* code 5DDE */
  ,{  11,  11,  2, acGUI_Fonthuawen12_5E74 } /* code 5E74 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_6548 } /* code 6548 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_65E5 } /* code 65E5 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_65F6 } /* code 65F6 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_6708 } /* code 6708 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_673A } /* code 673A */
  ,{  11,  11,  2, acGUI_Fonthuawen12_6C11 } /* code 6C11 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_6E05 } /* code 6E05 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_6EE4 } /* code 6EE4 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_786E } /* code 786E */
  ,{  11,  11,  2, acGUI_Fonthuawen12_79D2 } /* code 79D2 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_7A7A } /* code 7A7A */
  ,{  11,  11,  2, acGUI_Fonthuawen12_7EC4 } /* code 7EC4 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_7F6E } /* code 7F6E */
  ,{  11,  11,  2, acGUI_Fonthuawen12_83B1 } /* code 83B1 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_8BBE } /* code 8BBE */
  ,{  11,  11,  2, acGUI_Fonthuawen12_8C03 } /* code 8C03 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_8FC7 } /* code 8FC7 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_95F4 } /* code 95F4 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_9662 } /* code 9662 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_96F6 } /* code 96F6 */
  ,{  11,  11,  2, acGUI_Fonthuawen12_9AD8 } /* code 9AD8 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop37 = {
   0x9AD8 /* first character */
  ,0x9AD8 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 36] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop36 = {
   0x96F6 /* first character */
  ,0x96F6 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 35] /* address of first character */
  ,&GUI_Fonthuawen12_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop35 = {
   0x9662 /* first character */
  ,0x9662 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 34] /* address of first character */
  ,&GUI_Fonthuawen12_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop34 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 33] /* address of first character */
  ,&GUI_Fonthuawen12_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop33 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 32] /* address of first character */
  ,&GUI_Fonthuawen12_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop32 = {
   0x8C03 /* first character */
  ,0x8C03 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 31] /* address of first character */
  ,&GUI_Fonthuawen12_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop31 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 30] /* address of first character */
  ,&GUI_Fonthuawen12_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop30 = {
   0x83B1 /* first character */
  ,0x83B1 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 29] /* address of first character */
  ,&GUI_Fonthuawen12_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop29 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 28] /* address of first character */
  ,&GUI_Fonthuawen12_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop28 = {
   0x7EC4 /* first character */
  ,0x7EC4 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 27] /* address of first character */
  ,&GUI_Fonthuawen12_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop27 = {
   0x7A7A /* first character */
  ,0x7A7A /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 26] /* address of first character */
  ,&GUI_Fonthuawen12_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop26 = {
   0x79D2 /* first character */
  ,0x79D2 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 25] /* address of first character */
  ,&GUI_Fonthuawen12_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop25 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 24] /* address of first character */
  ,&GUI_Fonthuawen12_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop24 = {
   0x6EE4 /* first character */
  ,0x6EE4 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 23] /* address of first character */
  ,&GUI_Fonthuawen12_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop23 = {
   0x6E05 /* first character */
  ,0x6E05 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 22] /* address of first character */
  ,&GUI_Fonthuawen12_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop22 = {
   0x6C11 /* first character */
  ,0x6C11 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 21] /* address of first character */
  ,&GUI_Fonthuawen12_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop21 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 20] /* address of first character */
  ,&GUI_Fonthuawen12_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop20 = {
   0x6708 /* first character */
  ,0x6708 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 19] /* address of first character */
  ,&GUI_Fonthuawen12_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop19 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 18] /* address of first character */
  ,&GUI_Fonthuawen12_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop18 = {
   0x65E5 /* first character */
  ,0x65E5 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 17] /* address of first character */
  ,&GUI_Fonthuawen12_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop17 = {
   0x6548 /* first character */
  ,0x6548 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 16] /* address of first character */
  ,&GUI_Fonthuawen12_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop16 = {
   0x5E74 /* first character */
  ,0x5E74 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 15] /* address of first character */
  ,&GUI_Fonthuawen12_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop15 = {
   0x5DDE /* first character */
  ,0x5DDE /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 14] /* address of first character */
  ,&GUI_Fonthuawen12_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop14 = {
   0x5C11 /* first character */
  ,0x5C11 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 13] /* address of first character */
  ,&GUI_Fonthuawen12_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop13 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 12] /* address of first character */
  ,&GUI_Fonthuawen12_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop12 = {
   0x589E /* first character */
  ,0x589E /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 11] /* address of first character */
  ,&GUI_Fonthuawen12_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop11 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[ 10] /* address of first character */
  ,&GUI_Fonthuawen12_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop10 = {
   0x533B /* first character */
  ,0x533B /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[  9] /* address of first character */
  ,&GUI_Fonthuawen12_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop9 = {
   0x5316 /* first character */
  ,0x5316 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[  8] /* address of first character */
  ,&GUI_Fonthuawen12_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop8 = {
   0x52A0 /* first character */
  ,0x52A0 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[  7] /* address of first character */
  ,&GUI_Fonthuawen12_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop7 = {
   0x521D /* first character */
  ,0x521D /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[  6] /* address of first character */
  ,&GUI_Fonthuawen12_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop6 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[  5] /* address of first character */
  ,&GUI_Fonthuawen12_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop5 = {
   0x51CF /* first character */
  ,0x51CF /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[  4] /* address of first character */
  ,&GUI_Fonthuawen12_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop4 = {
   0x51C0 /* first character */
  ,0x51C0 /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[  3] /* address of first character */
  ,&GUI_Fonthuawen12_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop3 = {
   0x4EBA /* first character */
  ,0x4EBA /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[  2] /* address of first character */
  ,&GUI_Fonthuawen12_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop2 = {
   0x4E9A /* first character */
  ,0x4E9A /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[  1] /* address of first character */
  ,&GUI_Fonthuawen12_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonthuawen12_Prop1 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_Fonthuawen12_CharInfo[  0] /* address of first character */
  ,&GUI_Fonthuawen12_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fonthuawen12 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,12 /* height of font  */
  ,12 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fonthuawen12_Prop1}
  ,9 /* Baseline */
  ,4 /* Height of lowercase characters */
  ,6 /* Height of capital characters */
};

