/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: kaiti16.c                                             *
* Font:        ÐÂËÎÌå                                                *
* Height:      12                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  12                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\111.txt          *
*                                                                    *
**********************************************************************
*/

#include "CUIGUI_FONT.H"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontkaiti16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0020[ 12] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0030[ 12] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0031[ 12] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  __X_____,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0032[ 12] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  ___X____,
  __X_____,
  _X______,
  X_______,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0033[ 12] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  _XXX____,
  X___X___,
  ____X___,
  __XX____,
  ____X___,
  ____X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0034[ 12] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ___X____,
  __XX____,
  _X_X____,
  _X_X____,
  X__X____,
  _XXXX___,
  ___X____,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0035[ 12] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  XXXXX___,
  X_______,
  X_______,
  XXXX____,
  ____X___,
  ____X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0036[ 12] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  _XXX____,
  X__X____,
  X_______,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0037[ 12] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  XXXXX___,
  X__X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0038[ 12] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0039[ 12] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ____X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_003A[ 12] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_4E2D[ 24] = { /* code 4E2D */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _____X__,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_4E9A[ 24] = { /* code 4E9A */
  ________,________,
  _XXXXXXX,XX______,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  X__X___X,__X_____,
  _X_X___X,_X______,
  __XX___X,X_______,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_4EBA[ 24] = { /* code 4EBA */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ____X_X_,________,
  ____X_X_,________,
  ___X___X,________,
  ___X___X,________,
  __X_____,X_______,
  _X______,_X______,
  X_______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_51C0[ 24] = { /* code 51C0 */
  ____X___,________,
  ____XXXX,X_______,
  X__X____,X_______,
  _X_____X,________,
  ___XXXXX,XX______,
  ______X_,_X______,
  __XXXXXX,XXX_____,
  ______X_,_X______,
  _X_XXXXX,XX______,
  X_____X_,_X______,
  ______X_,________,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_51CF[ 24] = { /* code 51CF */
  ________,X_X_____,
  ________,X_______,
  X_XXXXXX,XXX_____,
  _XX_____,X_______,
  __X_XXX_,X_______,
  __X_____,X_X_____,
  __X_XXX_,X_X_____,
  __X_X_X_,XX______,
  _XX_X_X_,XX______,
  X_X_XXX_,X_X_____,
  __X____X,_XX_____,
  _X____X_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5206[ 24] = { /* code 5206 */
  ___X___X,________,
  ___X___X,________,
  __X_____,X_______,
  __X_____,X_______,
  _X______,_X______,
  X_XXXXXX,X_X_____,
  ____X___,X_______,
  ____X___,X_______,
  ___X____,X_______,
  ___X____,X_______,
  __X_____,X_______,
  _X___XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_521D[ 24] = { /* code 521D */
  _X______,________,
  __X__XXX,XXX_____,
  XXXX__X_,__X_____,
  ___X__X_,__X_____,
  __X___X_,__X_____,
  __X_X_X_,__X_____,
  _XXX__X_,__X_____,
  X_X_X_X_,__X_____,
  __X___X_,__X_____,
  __X__X__,__X_____,
  __X__X__,__X_____,
  __X_X___,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_52A0[ 24] = { /* code 52A0 */
  __X_____,________,
  __X_____,________,
  __X____X,XXX_____,
  XXXXXX_X,__X_____,
  __X__X_X,__X_____,
  __X__X_X,__X_____,
  __X__X_X,__X_____,
  __X__X_X,__X_____,
  __X__X_X,__X_____,
  _X___X_X,__X_____,
  _X___X_X,XXX_____,
  X__XX__X,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5316[ 24] = { /* code 5316 */
  ___X__X_,________,
  ___X__X_,________,
  __X___X_,__X_____,
  __X___X_,_X______,
  _XX___X_,X_______,
  X_X___XX,________,
  __X___X_,________,
  __X__XX_,________,
  __X_X_X_,________,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_533B[ 24] = { /* code 533B */
  ________,________,
  _XXXXXXX,XXX_____,
  _X__X___,________,
  _X__X___,________,
  _X_XXXXX,XX______,
  _XX___X_,________,
  _X____X_,________,
  _XXXXXXX,XXX_____,
  _X___X_X,________,
  _X__X___,X_______,
  _X_X____,_X______,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5668[ 24] = { /* code 5668 */
  _XXXX_XX,XX______,
  _X__X_X_,_X______,
  _XXXX_XX,XX______,
  _____X__,X_______,
  _____X__,_X______,
  XXXXXXXX,XXX_____,
  ____X_X_,________,
  __XX___X,X_______,
  XX______,_XX_____,
  _XXXX_XX,XX______,
  _X__X_X_,_X______,
  _XXXX_XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_589E[ 24] = { /* code 589E */
  __X__X__,_X______,
  __X_XXXX,XXX_____,
  __X_X__X,__X_____,
  __X_XX_X,_XX_____,
  XXXXX__X,__X_____,
  __X_XXXX,XXX_____,
  __X_____,________,
  __X__XXX,XX______,
  __X__X__,_X______,
  __XX_XXX,XX______,
  XX___X__,_X______,
  _____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5B9A[ 24] = { /* code 5B9A */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  ________,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  __X__X__,________,
  __X__XXX,XX______,
  __X__X__,________,
  _X_X_X__,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5C11[ 24] = { /* code 5C11 */
  _____X__,________,
  _____X__,________,
  __X__X__,X_______,
  __X__X__,_X______,
  _X___X__,__X_____,
  X____X__,__X_____,
  _____X__,________,
  _____X__,X_______,
  _______X,________,
  _____XX_,________,
  ___XX___,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5DDE[ 24] = { /* code 5DDE */
  ___X____,__X_____,
  ___X__X_,__X_____,
  ___X__X_,__X_____,
  _X_X__X_,__X_____,
  _X_XX_X_,X_X_____,
  X__X_XX_,_XX_____,
  ___X__X_,__X_____,
  ___X__X_,__X_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  _X____X_,__X_____,
  X_______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5E02[ 24] = { /* code 5E02 */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  _____X__,________,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  _X___X__,XX______,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5E74[ 24] = { /* code 5E74 */
  __X_____,________,
  __X_____,________,
  __XXXXXX,XXX_____,
  _X____X_,________,
  X_____X_,________,
  __XXXXXX,XX______,
  __X___X_,________,
  __X___X_,________,
  XXXXXXXX,XXX_____,
  ______X_,________,
  ______X_,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6548[ 24] = { /* code 6548 */
  __X____X,________,
  ___X___X,________,
  XXXXXX_X,________,
  _______X,XXX_____,
  _X__X_X_,_X______,
  _X___X_X,_X______,
  X______X,_X______,
  __X_X__X,_X______,
  ___X____,X_______,
  __X_X___,X_______,
  _X___X_X,_X______,
  X_____X_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_65E5[ 24] = { /* code 65E5 */
  ________,________,
  _XXXXXXX,XX______,
  _X______,_X______,
  _X______,_X______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X______,_X______,
  _X______,_X______,
  _X______,_X______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_65F6[ 24] = { /* code 65F6 */
  ________,_X______,
  XXXX____,_X______,
  X__X____,_X______,
  X__X_XXX,XXX_____,
  X__X____,_X______,
  XXXX____,_X______,
  X__X__X_,_X______,
  X__X___X,_X______,
  X__X___X,_X______,
  XXXX____,_X______,
  X__X____,_X______,
  _______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6708[ 24] = { /* code 6708 */
  ________,________,
  __XXXXXX,XX______,
  __X_____,_X______,
  __X_____,_X______,
  __XXXXXX,XX______,
  __X_____,_X______,
  __X_____,_X______,
  __XXXXXX,XX______,
  __X_____,_X______,
  _X______,_X______,
  _X______,_X______,
  X______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_673A[ 24] = { /* code 673A */
  __X_____,________,
  __X__XXX,X_______,
  __X__X__,X_______,
  XXXX_X__,X_______,
  __X__X__,X_______,
  _XXX_X__,X_______,
  _XX_XX__,X_______,
  X_X__X__,X_______,
  __X__X__,X_______,
  __X__X__,X_X_____,
  __X_X___,X_X_____,
  __XX____,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6C11[ 24] = { /* code 6C11 */
  _XXXXXXX,XX______,
  _X______,_X______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X____X_,________,
  _X____X_,________,
  _XXXXXXX,XXX_____,
  _X____X_,________,
  _X_____X,________,
  _X_X____,X_X_____,
  _XX_____,_XX_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6E05[ 24] = { /* code 6E05 */
  ______X_,________,
  X_XXXXXX,XXX_____,
  _X____X_,________,
  ___XXXXX,XX______,
  ______X_,________,
  X_XXXXXX,XXX_____,
  _X_X____,_X______,
  ___XXXXX,XX______,
  ___X____,_X______,
  _X_XXXXX,XX______,
  X__X____,_X______,
  ___X____,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6EE4[ 24] = { /* code 6EE4 */
  ______XX,XX______,
  X_____X_,________,
  _X_XXXXX,XXX_____,
  ___X__X_,__X_____,
  ___X__XX,X_______,
  X__XXXX_,__X_____,
  _X_X___X,XXX_____,
  ___X__X_,________,
  ___X___X,________,
  _X_X_X__,_X______,
  X__XX_X_,X_X_____,
  __X___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_786E[ 24] = { /* code 786E */
  ______X_,________,
  XXXX__XX,XX______,
  __X__X__,_X______,
  __X_____,X_______,
  _X___XXX,XXX_____,
  _XXX_X_X,__X_____,
  XX_X_XXX,XXX_____,
  _X_X_X_X,__X_____,
  _X_X_XXX,XXX_____,
  _XXX_X_X,__X_____,
  _X_X_X_X,__X_____,
  ____X___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_79D2[ 24] = { /* code 79D2 */
  ___X___X,________,
  XXX____X,________,
  __X____X,_X______,
  __X__X_X,__X_____,
  XXXX_X_X,__X_____,
  __X__X_X,__X_____,
  _XX_X__X,________,
  _XXX___X,__X_____,
  X_X_____,_X______,
  __X_____,X_______,
  __X___XX,________,
  __X_XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_7A7A[ 24] = { /* code 7A7A */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  X__X___X,__X_____,
  __X_____,X_______,
  _X______,_X______,
  ________,________,
  _XXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_7EC4[ 24] = { /* code 7EC4 */
  __X_____,________,
  __X__XXX,XX______,
  _X___X__,_X______,
  X__X_X__,_X______,
  XXX__XXX,XX______,
  __X__X__,_X______,
  _X___X__,_X______,
  XXXX_XXX,XX______,
  _____X__,_X______,
  __XX_X__,_X______,
  XX___X__,_X______,
  ____XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_7F6E[ 24] = { /* code 7F6E */
  _XXXXXXX,XX______,
  _X__X_X_,_X______,
  _XXXXXXX,XX______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  __XXXXXX,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X__X__,X_______,
  __X__X__,X_______,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_83B1[ 24] = { /* code 83B1 */
  ___X___X,________,
  XXXXXXXX,XXX_____,
  ___X___X,________,
  _____X__,________,
  _XXXXXXX,XX______,
  __X__X__,X_______,
  ___X_X_X,________,
  XXXXXXXX,XXX_____,
  ____XXX_,________,
  __XX_X_X,X_______,
  XX___X__,_XX_____,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_8BBE[ 24] = { /* code 8BBE */
  _X___XXX,X_______,
  __X__X__,X_______,
  _____X__,X_______,
  _____X__,X_______,
  XXX_X___,_XX_____,
  __X_____,________,
  __X_XXXX,XX______,
  __X__X__,_X______,
  __X___X_,X_______,
  __XX___X,________,
  __X___X_,X_______,
  ____XX__,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_8C03[ 24] = { /* code 8C03 */
  X___XXXX,XXX_____,
  _X__X___,__X_____,
  ____X__X,__X_____,
  ____X_XX,X_X_____,
  XX__X__X,__X_____,
  _X__XXXX,XXX_____,
  _X__X___,__X_____,
  _X__X_XX,X_X_____,
  _X__X_X_,X_X_____,
  _XX_X_XX,X_X_____,
  _X__X___,__X_____,
  ___X____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_8FC7[ 24] = { /* code 8FC7 */
  _X______,_X______,
  __X_____,_X______,
  ________,_X______,
  ____XXXX,XXX_____,
  XXX_____,_X______,
  __X__X__,_X______,
  __X___X_,_X______,
  __X___X_,_X______,
  __X_____,_X______,
  __X____X,XX______,
  _X_X____,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_95F4[ 24] = { /* code 95F4 */
  _X__XXXX,XXX_____,
  __X_____,__X_____,
  ________,__X_____,
  _X_XXXXX,X_X_____,
  _X_X____,X_X_____,
  _X_X____,X_X_____,
  _X_XXXXX,X_X_____,
  _X_X____,X_X_____,
  _X_X____,X_X_____,
  _X_XXXXX,X_X_____,
  _X______,__X_____,
  _X______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_9662[ 24] = { /* code 9662 */
  ______X_,________,
  XXX____X,________,
  X_X_XXXX,XXX_____,
  X_X_X___,__X_____,
  XX______,________,
  X_X__XXX,XX______,
  X_X_____,________,
  X_X_XXXX,XXX_____,
  XX____X_,X_______,
  X_____X_,X_______,
  X____X__,X_X_____,
  X___X___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_96F6[ 24] = { /* code 96F6 */
  _XXXXXXX,XX______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  X_XX_X_X,X_X_____,
  _____X__,________,
  _XXX_X_X,XX______,
  ____X_X_,________,
  __XX_X_X,X_______,
  XX_XXXXX,_XX_____,
  ______X_,________,
  ___XXX__,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_9AD8[ 24] = { /* code 9AD8 */
  _____X__,________,
  XXXXXXXX,XXX_____,
  ________,________,
  __XXXXXX,X_______,
  __X_____,X_______,
  __XXXXXX,X_______,
  ________,________,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  X__XXXXX,__X_____,
  X__X___X,__X_____,
  X__XXXXX,_XX_____};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontkaiti16_CharInfo[50] = {
   {   6,   6,  1, acGUI_Fontkaiti16_0020 } /* code 0020 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_0030 } /* code 0030 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_0031 } /* code 0031 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_0032 } /* code 0032 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_0033 } /* code 0033 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_0034 } /* code 0034 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_0035 } /* code 0035 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_0036 } /* code 0036 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_0037 } /* code 0037 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_0038 } /* code 0038 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_0039 } /* code 0039 */
  ,{   6,   6,  1, acGUI_Fontkaiti16_003A } /* code 003A */
  ,{  12,  12,  2, acGUI_Fontkaiti16_4E2D } /* code 4E2D */
  ,{  12,  12,  2, acGUI_Fontkaiti16_4E9A } /* code 4E9A */
  ,{  12,  12,  2, acGUI_Fontkaiti16_4EBA } /* code 4EBA */
  ,{  12,  12,  2, acGUI_Fontkaiti16_51C0 } /* code 51C0 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_51CF } /* code 51CF */
  ,{  12,  12,  2, acGUI_Fontkaiti16_5206 } /* code 5206 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_521D } /* code 521D */
  ,{  12,  12,  2, acGUI_Fontkaiti16_52A0 } /* code 52A0 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_5316 } /* code 5316 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_533B } /* code 533B */
  ,{  12,  12,  2, acGUI_Fontkaiti16_5668 } /* code 5668 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_589E } /* code 589E */
  ,{  12,  12,  2, acGUI_Fontkaiti16_5B9A } /* code 5B9A */
  ,{  12,  12,  2, acGUI_Fontkaiti16_5C11 } /* code 5C11 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_5DDE } /* code 5DDE */
  ,{  12,  12,  2, acGUI_Fontkaiti16_5E02 } /* code 5E02 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_5E74 } /* code 5E74 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_6548 } /* code 6548 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_65E5 } /* code 65E5 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_65F6 } /* code 65F6 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_6708 } /* code 6708 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_673A } /* code 673A */
  ,{  12,  12,  2, acGUI_Fontkaiti16_6C11 } /* code 6C11 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_6E05 } /* code 6E05 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_6EE4 } /* code 6EE4 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_786E } /* code 786E */
  ,{  12,  12,  2, acGUI_Fontkaiti16_79D2 } /* code 79D2 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_7A7A } /* code 7A7A */
  ,{  12,  12,  2, acGUI_Fontkaiti16_7EC4 } /* code 7EC4 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_7F6E } /* code 7F6E */
  ,{  12,  12,  2, acGUI_Fontkaiti16_83B1 } /* code 83B1 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_8BBE } /* code 8BBE */
  ,{  12,  12,  2, acGUI_Fontkaiti16_8C03 } /* code 8C03 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_8FC7 } /* code 8FC7 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_95F4 } /* code 95F4 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_9662 } /* code 9662 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_96F6 } /* code 96F6 */
  ,{  12,  12,  2, acGUI_Fontkaiti16_9AD8 } /* code 9AD8 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop40 = {
   0x9AD8 /* first character */
  ,0x9AD8 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 49] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop39 = {
   0x96F6 /* first character */
  ,0x96F6 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 48] /* address of first character */
  ,&GUI_Fontkaiti16_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop38 = {
   0x9662 /* first character */
  ,0x9662 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 47] /* address of first character */
  ,&GUI_Fontkaiti16_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop37 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 46] /* address of first character */
  ,&GUI_Fontkaiti16_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop36 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 45] /* address of first character */
  ,&GUI_Fontkaiti16_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop35 = {
   0x8C03 /* first character */
  ,0x8C03 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 44] /* address of first character */
  ,&GUI_Fontkaiti16_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop34 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 43] /* address of first character */
  ,&GUI_Fontkaiti16_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop33 = {
   0x83B1 /* first character */
  ,0x83B1 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 42] /* address of first character */
  ,&GUI_Fontkaiti16_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop32 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 41] /* address of first character */
  ,&GUI_Fontkaiti16_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop31 = {
   0x7EC4 /* first character */
  ,0x7EC4 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 40] /* address of first character */
  ,&GUI_Fontkaiti16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop30 = {
   0x7A7A /* first character */
  ,0x7A7A /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 39] /* address of first character */
  ,&GUI_Fontkaiti16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop29 = {
   0x79D2 /* first character */
  ,0x79D2 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 38] /* address of first character */
  ,&GUI_Fontkaiti16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop28 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 37] /* address of first character */
  ,&GUI_Fontkaiti16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop27 = {
   0x6EE4 /* first character */
  ,0x6EE4 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 36] /* address of first character */
  ,&GUI_Fontkaiti16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop26 = {
   0x6E05 /* first character */
  ,0x6E05 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 35] /* address of first character */
  ,&GUI_Fontkaiti16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop25 = {
   0x6C11 /* first character */
  ,0x6C11 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 34] /* address of first character */
  ,&GUI_Fontkaiti16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop24 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 33] /* address of first character */
  ,&GUI_Fontkaiti16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop23 = {
   0x6708 /* first character */
  ,0x6708 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 32] /* address of first character */
  ,&GUI_Fontkaiti16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop22 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 31] /* address of first character */
  ,&GUI_Fontkaiti16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop21 = {
   0x65E5 /* first character */
  ,0x65E5 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontkaiti16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop20 = {
   0x6548 /* first character */
  ,0x6548 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontkaiti16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop19 = {
   0x5E74 /* first character */
  ,0x5E74 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontkaiti16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop18 = {
   0x5E02 /* first character */
  ,0x5E02 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontkaiti16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop17 = {
   0x5DDE /* first character */
  ,0x5DDE /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontkaiti16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop16 = {
   0x5C11 /* first character */
  ,0x5C11 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontkaiti16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop15 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontkaiti16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop14 = {
   0x589E /* first character */
  ,0x589E /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 23] /* address of first character */
  ,&GUI_Fontkaiti16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop13 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontkaiti16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop12 = {
   0x533B /* first character */
  ,0x533B /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontkaiti16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop11 = {
   0x5316 /* first character */
  ,0x5316 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontkaiti16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop10 = {
   0x52A0 /* first character */
  ,0x52A0 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 19] /* address of first character */
  ,&GUI_Fontkaiti16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop9 = {
   0x521D /* first character */
  ,0x521D /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontkaiti16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop8 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontkaiti16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop7 = {
   0x51CF /* first character */
  ,0x51CF /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontkaiti16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop6 = {
   0x51C0 /* first character */
  ,0x51C0 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontkaiti16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop5 = {
   0x4EBA /* first character */
  ,0x4EBA /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontkaiti16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop4 = {
   0x4E9A /* first character */
  ,0x4E9A /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontkaiti16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop3 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontkaiti16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop2 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontkaiti16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontkaiti16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontkaiti16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,12 /* height of font  */
  ,12 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontkaiti16_Prop1}
  ,10 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

