/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: xingkai24.c                                           *
* Font:        »ªÎÄÐÐ¿¬                                              *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\1                *
* Read pattern file: C:\Users\Administrator\Desktop\1.txt            *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\1.txt            *
*                                                                    *
**********************************************************************
*/
#include "CUIGUI_FONT.H"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontxingkai24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_0020[ 24] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_0021[ 24] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  ________,
  ________,
  _______X,
  _______X,
  ______XX,
  _____XXX,
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __X_____,
  __XX____,
  _XXX____,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_4E00[ 72] = { /* code 4E00, <CJK Ideograph, First> */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_____XXX,XXX_____,
  _______X,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,X____XXX,XXXX____,
  ____XXX_,____X___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_4F60[ 72] = { /* code 4F60 */
  ________,________,________,
  ________,__XX____,________,
  ________,____XX__,________,
  ______X_,____XX__,________,
  ______XX,____XX__,________,
  ______XX,X__XX_XX,XX______,
  _____XXX,X__XXXXX,XXX_____,
  _____XXX,__XXXXXX,XXX_____,
  ____XXX_,__XXX__X,XX______,
  ____XXX_,__XXX_XX,________,
  ___XXX__,__X_XXX_,________,
  ___XXXX_,_____XX_,________,
  ____XXX_,_____XXX,XXX_____,
  _____XX_,___XXXX_,_XXX____,
  _____XX_,XXX__XX_,XXXX____,
  _____XX_,XXX__XX_,_XXX____,
  _____XX_,XX_XXXX_,________,
  _____XX_,____XXX_,________,
  ______X_,_____X__,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_535A[ 72] = { /* code 535A */
  ________,_____XX_,________,
  ________,_____XX_,__X_____,
  _____XX_,_____XXX,X_XXX___,
  _____XX_,___XXXXX,__XX____,
  _____XX_,____XXXX,________,
  _____XXX,____XXXX,XX______,
  ____XXXX,_X_XXXXX,_X______,
  ___XXXX_,__XX__XX,_X______,
  _XXXXX__,__XXXXXX,_X______,
  __XXXX__,__X_XXXX,_X______,
  _____X__,__XXXXXX,_X______,
  _____X__,__X_XXXX,XXX_____,
  _____X__,__XXXXXX,XXXX____,
  _____X__,XXXX___X,X_______,
  _____X__,_XXXX__X,X_______,
  _____X__,____XX_X,X_______,
  _____X__,___XX__X,X_______,
  _____X__,__X____X,X_______,
  _____X__,___XXXXX,X_______,
  ________,_____XXX,________,
  ________,______XX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_548C[ 72] = { /* code 548C */
  ________,________,________,
  ________,__X_____,________,
  ________,_XXX____,________,
  _______X,XXXX____,________,
  _____XXX,X_______,________,
  ___XX___,XX______,________,
  __X_____,XXX_____,________,
  _______X,XX______,_XX_____,
  _____XXX,X______X,XXXX____,
  __XXXXXX,XX_XX_XX,X_XXX___,
  ___XXXX_,XXXXXXX_,_XXX____,
  ________,XXX__X__,_XXX____,
  _______X,XX___XXX,XXX_____,
  _____XXX,X____XXX,XXX_____,
  _____XXX,X____XX_,________,
  _____XX_,X_______,________,
  _______X,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_5988[ 72] = { /* code 5988 */
  ________,X_______,________,
  ________,_X______,________,
  ________,_X_____X,X_______,
  ________,_XX__XXX,XX______,
  ________,_XX_XXXX,XX______,
  ________,_XX_X__X,X_______,
  ____X___,XX_X_X_X,X_______,
  ____XX__,XXX__XXX,X_______,
  ____XX__,XX___X_X,X_______,
  _____XXX,XX__XXXX,XXXX____,
  _____XXX,XX__XXXX,XXXXX___,
  ____XXX_,XX__XXX_,___XX___,
  ___XXXXX,XX__X__X,___XX___,
  ___XX__X,XX___XXX,X__X____,
  ____XX__,XXXXXX__,__XX____,
  _____XXX,X_XXX___,__XX____,
  ______XX,X____X__,_XX_____,
  ________,X_____XX,XX______,
  ________,_______X,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_5BF8[ 72] = { /* code 5BF8 */
  ________,________,________,
  ________,_____XX_,________,
  ________,____X_XX,________,
  ________,______XX,________,
  ________,______XX,________,
  ________,______XX,XX______,
  ________,____XXXX,XXX_____,
  ________,__XXXXXX,________,
  ________,XXXXX_XX,________,
  _____XXX,XXX___X_,________,
  ______XX,X_____X_,________,
  ________,______X_,________,
  ________,XXX___X_,________,
  _______X,_XXX__XX,________,
  ________,X_____XX,________,
  ________,_XX___XX,________,
  ________,__XXXXXX,________,
  ________,___XXXXX,________,
  ________,_____XXX,________,
  ________,______X_,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_5BF9[ 72] = { /* code 5BF9 */
  ________,_______X,X_______,
  ________,________,XX______,
  ________,________,_X______,
  ________,________,_X______,
  ________,XXX_____,_X_XX___,
  ______XX,XXXX____,_XXXX___,
  ______XX,XXXX__XX,XXXXX___,
  ________,_XXXXXXX,XX______,
  ________,_XX_XXXX,_X______,
  ____XXXX,XXXX____,_X______,
  _____XXX,XXX_X___,_X______,
  _______X,XXXXXXX_,_X______,
  ______XX,XXXX_XX_,_X______,
  ______XX,__XX____,_X______,
  ____XXX_,___X____,_X______,
  ________,_____XX_,_X______,
  ________,______XX,XX______,
  ________,_______X,XX______,
  ________,________,XX______,
  ________,________,_X______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_5D14[ 72] = { /* code 5D14 */
  ________,___XX__X,X_______,
  ________,___XX__X,XX______,
  _______X,__XXX__X,X_______,
  _______X,XXXXXXX_,________,
  _____XXX,XXXX____,________,
  _____XXX,XXXXXXX_,________,
  ______X_,XXX__XX_,________,
  _______X,XX___XXX,X_______,
  _______X,XX_XXXX_,________,
  ______XX,_XXXXXXX,________,
  _____XX_,_X__XXXX,________,
  ____XX__,_XXXXXX_,________,
  ___XX___,X__XXXXX,________,
  ___X____,X_XXXXXX,________,
  ________,X_XXXXX_,________,
  ________,X___XXXX,________,
  ________,XXXXXXXX,X_______,
  ________,X_XX____,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_5E08[ 72] = { /* code 5E08 */
  ________,________,________,
  ______XX,______XX,XX______,
  _____X_X,X__XXXXX,XX______,
  _____X_X,X_XXXXX_,________,
  _____X_X,XX__XXX_,________,
  ___X_X_X,X____XXX,X_______,
  ___XXX_X,_____XXX,XX______,
  ____XX_X,__X_XXX_,XX______,
  ____XX_X,__XXXXX_,XX______,
  ____XX_X,__XX_XX_,XX______,
  ____XX_X,__XX_XX_,XX______,
  ___XX__X,__XX_XXX,XX______,
  ____X__X,__X__XXX,XX______,
  ______XX,__X__XX_,X_______,
  ______XX,_____XX_,X_______,
  ______X_,_____XX_,________,
  ______X_,_____XX_,________,
  ________,_____XX_,________,
  ________,_____X__,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_5FC3[ 72] = { /* code 5FC3 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,XXX_____,
  ________,_______X,X_XX____,
  ________,_XX___XX,_XXXX___,
  ________,__XXXXX_,XXXX____,
  ____X__X,__XXXX__,________,
  ____X__X,X__XXXX_,________,
  ____XX_X,X___X_XX,________,
  ___XXX__,X______X,X_______,
  ___XX___,XX_____X,XXX_____,
  ____X___,_XXXXXXX,XXX_____,
  ____X___,___XXXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_6069[ 72] = { /* code 6069 */
  ________,________,________,
  ________,___XXXX_,________,
  ________,_XXXXXXX,________,
  ________,XXXX__XX,________,
  _______X,__XX__XX,________,
  _______X,__XXXXXX,________,
  _______X,XXXXX_XX,________,
  _______X,XXXX__XX,________,
  _______X,_XXXXXXX,________,
  _______X,XXX___XX,________,
  ________,XXXXXXXX,________,
  _______X,XX____X_,________,
  ________,___X____,XXXX____,
  _____XXX,___XXXXX,_XXX____,
  _____X_X,X__XXXX_,__XXX___,
  ____XX__,X__XX__X,________,
  ____XX__,XX_____X,X_______,
  ____XX__,_XXXXXXX,XX______,
  ________,___XXXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_60A8[ 72] = { /* code 60A8 */
  ________,___XX___,________,
  ________,____XX__,________,
  _______X,X___XX__,________,
  _______X,XX__X___,________,
  ______XX,XX_XX_XX,X_______,
  ______XX,___XXXXX,XX______,
  _____XX_,__XXX_XX,X_______,
  ____XXX_,__XX_X__,________,
  ____XXXX,_X___XXX,X_______,
  ____X_XX,_XX__XXX,X_______,
  ______XX,_XX__X__,________,
  ______XX,_X__XX__,________,
  ______X_,_X___X__,________,
  ______XX,__XX___X,XXXX____,
  ____XX_X,__XXXXX_,_XXX____,
  ____XX_X,X_XXXX__,___X____,
  ____X___,X__XX_XX,________,
  ___XX___,XX_____X,X_______,
  ____X___,_XXXXXXX,XX______,
  ____X___,___XXXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_610F[ 72] = { /* code 610F */
  ________,__XXX___,________,
  ________,__XXXX__,________,
  ________,_XXXXXX_,________,
  ________,XXXXXX__,________,
  ________,_XXXXX__,________,
  ________,XXX_XX__,________,
  ________,X_XXXXXX,XX______,
  _______X,XXXX____,________,
  __XXXXXX,__XXXXXX,________,
  __XXX__X,_XXXXXXX,________,
  _______X,XXXX__XX,________,
  _______X,XXXXX_X_,________,
  ________,X_XX_XX_,________,
  ________,XXXXXX__,________,
  ________,X__X____,XXXX____,
  ______XX,XX_XXXXX,XXXX____,
  ______XX,_X__XXX_,__XX____,
  _____XX_,_XX____X,________,
  _____XX_,__XXXXXX,XX______,
  ______X_,____XXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_656C[ 72] = { /* code 656C */
  ________,________,________,
  ________,_XX_____,________,
  _______X,_XXX__X_,________,
  _____XXX,_XXX_X_X,________,
  _____XX_,XXX_XX_X,________,
  ______XX,XX__X__X,________,
  _____XXX,XXXXX_X_,________,
  ___XXXXX,XX_X__XX,XX______,
  ____XXXX,X_X__XXX,X_______,
  _____XXX,XXX__XXX,________,
  ____XXX_,_XXX_X_X,________,
  ____X_X_,XXXXXX_X,________,
  __X__XXX,_XX_XXXX,________,
  ___XXXXX,_XX___XX,________,
  ___XX_X_,_XX__XXX,XX______,
  ___XXXX_,XX_XXX__,XXXX____,
  ____XXXX,XX______,_XXXXX__,
  ________,XX______,________,
  ________,_X______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_662F[ 72] = { /* code 662F */
  ________,__XXX___,________,
  ________,_XXXXX__,________,
  ________,_XX_XX__,________,
  ________,X___XX__,________,
  ________,XXX_XX__,________,
  ________,XXXXXX__,________,
  ________,XXX_XX__,________,
  ________,XXX_XX__,________,
  ________,XXXXX___,________,
  ________,XXXXXXXX,________,
  ______XX,XXXX____,________,
  _______X,XXXX_XX_,________,
  _____XXX,X_XXX_X_,________,
  ___XXX_X,X_XXXXX_,________,
  ______XX,__XX____,________,
  ______XX,XXXX____,________,
  _____XX_,__XXXXX_,________,
  ____XX__,____XXXX,XXXXX___,
  ___XX___,_______X,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_6653[ 72] = { /* code 6653 */
  ________,________,________,
  ________,__XXXX__,________,
  ________,__X__XX_,________,
  ________,___XX_XX,________,
  ________,___XXX_X,________,
  ______XX,____XXX_,________,
  ______XX,X___XXX_,XX______,
  _____X__,X__XXXXX,XX______,
  ____XX__,X__XXXXX,XX______,
  ____XX__,X_X_XX__,XX______,
  ____XXXX,XX_XX__X,X_______,
  ____XXXX,XXXX_XXX,X_______,
  ____XX_X,XXXXXXXX,X_______,
  ____XXX_,X__X__XX,________,
  ____XXX_,X____XX_,________,
  ____XXX_,X___XX__,________,
  _____XXX,X_XXX___,________,
  _____XXX,X_XX_XX_,__XXX___,
  ______X_,X______X,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_674E[ 72] = { /* code 674E */
  ________,__XXX___,________,
  ________,___XX___,________,
  ________,___XXXX_,________,
  ________,__XXXXXX,________,
  ________,_XXXX___,________,
  ______XX,XXXXX___,________,
  ___XXXXX,_XXXXXXX,________,
  ____XXX_,XXXXXXXX,X_______,
  _______X,XXX_XXX_,________,
  ______XX,X_XXXX__,________,
  _____XX_,_XXXXX__,________,
  ____XX__,XXX_XX__,________,
  ___X___X,X__XXX__,________,
  ________,__XXXXXX,________,
  ________,_XXX_XXX,________,
  _______X,X____XXX,________,
  ______XX,____XXX_,________,
  _______X,_____X__,________,
  _______X,X____X__,________,
  ________,XX__X___,________,
  ________,_XXX____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_6885[ 72] = { /* code 6885 */
  ________,________,________,
  ________,X___X___,________,
  ________,XX___XX_,________,
  ________,XX___XX_,________,
  ________,XX__XXXX,X_______,
  _______X,XXX_XXXX,X_______,
  _____XXX,XXX_X_XX,________,
  ____XXXX,X____X_X,X_______,
  __XXXXXX,X__X_XXX,XX______,
  ___XXX_X,X_X_X_XX,_X______,
  ____X__X,XX__X_XX,_X______,
  _______X,X__XXXXX,XXXX____,
  _____XXX,XXXXXXX_,XX_X____,
  ____XXXX,_XXX_XX_,X_______,
  ____XX_X,_XXXXXXX,XX______,
  _______X,_XXX_X__,XXX_____,
  _______X,_____X_X,X_______,
  _______X,______XX,________,
  _______X,______X_,________,
  ________,X_______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_6BCF[ 72] = { /* code 6BCF */
  ________,__X_____,________,
  ________,__XX____,________,
  ________,_XXX_XX_,________,
  ________,XXXXXXXX,________,
  _______X,XXXXXXX_,________,
  _______X,XXXXX___,________,
  ________,___XXXX_,________,
  ________,__XXXXXX,________,
  ________,_XX_X_XX,________,
  ________,_XX_X_XX,________,
  ________,_XXXXXXX,XXXX____,
  _____XXX,XX_XX_XX,___XX___,
  __XXXXXX,X__X__XX,________,
  ___XX_XX,X__X__XX,________,
  ______XX,X_XX__XX,________,
  ______XX,XXXXXXXX,X_______,
  ______XX,X_____X_,XX______,
  ________,_____XX_,________,
  ________,__XXXXX_,________,
  ________,___XXX__,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_6DF1[ 72] = { /* code 6DF1 */
  ________,________,________,
  _____X__,_X___XXX,X_______,
  ______XX,__XXXXX_,XX______,
  ______XX,_XXXX___,XX______,
  ____XXXX,_XX_XXXX,________,
  ___X____,XXXX_XX_,________,
  ___X____,X_XX__XX,________,
  ___XX___,__XX_X__,________,
  ___XX___,__XXXXXX,X_______,
  ___XX___,__XXXX__,________,
  ___XX___,_XXXXX__,________,
  ___X____,XXXXXX__,________,
  ___X__X_,__XXXXXX,________,
  ___XXXX_,__XX_XXX,XX______,
  ___XXXX_,_XX__X__,XXX_____,
  ____XXX_,XXX__X__,__XX____,
  ____XX__,___X_X__,________,
  _____X__,____XX__,________,
  ________,____XX__,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_6EE1[ 72] = { /* code 6EE1 */
  ________,______XX,________,
  ________,_______X,X_______,
  ________,__X____X,X_______,
  _____XX_,___XX__X,XX______,
  ______XX,X__XXXXX,XX______,
  _____XXX,XXXXX_XX,________,
  ____XXX_,_XXXXXX_,________,
  ________,___X_XXX,XXX_____,
  ___X____,_XXXX_X_,________,
  ___XXX__,XX_X__XX,________,
  ____XX__,_X_XXXXX,XX______,
  ____XX__,X__XXXX_,_XX_____,
  ____XX_X,XXXXXXX_,_XX_____,
  ____XX_X,X_XXX_XX,XXX_____,
  ____X_X_,X_XXXXX_,XXX_____,
  ____X_X_,X_X__X__,_XX_____,
  ____XXX_,X_X_____,_XX_____,
  _____XX_,X_____XX,XXX_____,
  _____X__,_______X,XX______,
  ________,________,_X______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_7075[ 72] = { /* code 7075 */
  ________,____XXX_,________,
  ________,_XXXXXXX,________,
  ________,XXX__XXX,________,
  ________,___X_XXX,________,
  _______X,XXXXXXX_,________,
  _______X,XXXXXX__,________,
  ________,XX__XX__,________,
  _______X,XXXXXX__,________,
  ______XX,X_XX____,________,
  ________,__X___XX,________,
  ________,_XX__XXX,________,
  _____X_X,XXXXXXX_,________,
  _____XXX,_XXX____,________,
  _____XX_,_XXXXX__,________,
  ________,XX___XX_,________,
  ________,XX____XX,________,
  ______XX,X______X,XX______,
  ____XXXX,________,XXXXX___,
  ________,________,_XXXXX__,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_7231[ 72] = { /* code 7231 */
  ________,______XX,________,
  ________,_____XXX,X_______,
  ________,___XXXXX,X_______,
  _______X,XXXX___X,________,
  ________,_XXXX__X,X_______,
  ______X_,X___XX_X,X_______,
  _______X,X___XXXX,________,
  _______X,X___XXXX,XXXX____,
  ____X__X,XXXXXX__,__XXX___,
  _____XXX,X___X___,_XXXX___,
  ____XX__,__XXXXXX,X_______,
  ____X___,XXXXX___,________,
  ____X__X,XXXXX_XX,________,
  ____X___,XXXX_XXX,________,
  _______X,XXX__XXX,________,
  _______X,X__XXXX_,________,
  ______XX,X__XXXX_,________,
  _____XXX,__XXXXXX,X_______,
  _____X__,XXXX___X,XXX_____,
  ________,________,_XXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_7238[ 72] = { /* code 7238 */
  ________,________,________,
  ________,________,________,
  _______X,____XXX_,________,
  _______X,X___XXXX,________,
  _______X,XX_XX___,________,
  _____XXX,___XX___,________,
  ________,XXXX____,________,
  ________,_XXXX___,________,
  ________,XXX__XX_,________,
  ______XX,X___XXXX,X_______,
  _____XXX,XXXXXXXX,XXXX____,
  ___XXXXX,__XX_X__,_XXXXX__,
  _______X,__XXX___,________,
  _______X,XXXXXX__,________,
  _______X,XX______,________,
  _______X,________,________,
  _______X,________,_X______,
  _______X,X_______,XX______,
  ________,XXXXXXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_7530[ 72] = { /* code 7530 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XXXXX,X_______,
  ________,XXXX____,XXX_____,
  _______X,XXXX____,XXX_____,
  ____X_XX,__XX____,XXX_____,
  ____XXX_,__XXXX__,XXX_____,
  ____XXX_,_XXXXX__,XX______,
  ____XXXX,XXXXXX__,XX______,
  _____XXX,XXXX____,XX______,
  _____XX_,_XXX___X,XX______,
  _____XX_,_XXX___X,XX______,
  ______XX,XXXXXX_X,X_______,
  _______X,X_____XX,X_______,
  ________,_______X,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_7684[ 72] = { /* code 7684 */
  ________,________,________,
  ________,_____XX_,________,
  ________,_____X_X,________,
  ______XX,_____X_X,________,
  ______XX,X___X__X,________,
  ______XX,X___X_X_,________,
  ____XXXX,___X__X_,________,
  ___X___X,XXX__XXX,XX______,
  ___XX_XX,XXX_XXX_,__XX____,
  ___XXXXX,_XX_XX__,__XX____,
  ___XXXX_,XXX__XX_,__XX____,
  ___XXX__,XXX_XXX_,__X_____,
  ___XXX_X,_XX_XXX_,_XX_____,
  ___XXX_X,_X__X___,_XX_____,
  ____XX_X,XX__X___,_XX_____,
  _____X__,XX___XX_,XX______,
  ________,XX___XXX,XX______,
  ________,______XX,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_7EAA[ 72] = { /* code 7EAA */
  ________,________,________,
  ________,________,________,
  _______X,________,________,
  _______X,X_______,________,
  ______XX,XX____XX,X_______,
  _____XXX,X____XXX,XX______,
  ____XXXX,___XXXXX,XX______,
  ___XXXX_,__XXXX_X,X_______,
  __XXXXXX,__X___XX,X_______,
  __XX_XXX,_X___XXX,________,
  _____XX_,X_XXXXXX,________,
  ____XXX_,X_XXXXXX,________,
  ___XXXXX,__XXX___,________,
  ___XX_XX,__XX____,___X____,
  ___X__XX,__X_____,___X____,
  _____XX_,__X_____,___X____,
  _____XX_,__X_____,_XXX____,
  ____XX__,___XXXXX,XXXX____,
  ____XX__,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_8001[ 72] = { /* code 8001 */
  ________,________,________,
  ________,________,________,
  ________,___XXX__,________,
  ________,____XX__,_X______,
  ________,____XXX_,XXX_____,
  ________,XXXXXXXX,XX______,
  ________,_XXXX_XX,X_______,
  ________,__XXXXXX,________,
  ________,___XXXXX,XXX_____,
  ________,__XXXXXX,XXX_____,
  _______X,XXXXXX__,________,
  ____XXXX,X__XX_X_,________,
  ____XXX_,__XX__XX,X_______,
  ____X___,_XXX_XXX,X_______,
  ________,_XXXXX__,________,
  ________,XX_X____,________,
  _______X,X__X____,_X______,
  ______XX,___X____,XX______,
  _____X__,___XXXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_83B9[ 72] = { /* code 83B9 */
  ________,_____XX_,________,
  ________,_____XXX,________,
  ________,XX____XX,________,
  ________,XXX___XX,X_______,
  ________,_XXXXXXX,XX______,
  ______XX,XXX__XX_,________,
  ______XX,XXX_XX__,________,
  ______X_,_X_XXXXX,XXX_____,
  _____X__,XXXX____,_XX_____,
  _____XXX,XX______,XXXX____,
  _____XX_,___XX_XX,XXXX____,
  ____XXX_,__XXXX__,________,
  ____XX__,_XXXX___,________,
  ____XX__,__X_X___,X_______,
  ____XX__,__XXXX__,XX______,
  ________,_XXXXX_X,XX______,
  ________,_XXXX___,X_______,
  ________,__XXX_X_,________,
  ________,_XXXXXX_,________,
  ________,XXXXXXX_,________,
  ________,_XX_____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_89D2[ 72] = { /* code 89D2 */
  ________,__XX____,________,
  ________,__XXX___,________,
  ________,_XXXXXX_,________,
  ________,XXXX_XX_,________,
  ______XX,XX__XXX_,________,
  _____XXX,___XXX__,________,
  ____XX__,_XXXXXXX,________,
  ____X___,X_XXXX_X,X_______,
  _______X,_XXXX__X,X_______,
  _______X,X__XXX_X,X_______,
  ______XX,_XXXXX_X,X_______,
  ______XX,XXXXXX_X,X_______,
  _______X,__XXX__X,X_______,
  _______X,_XXXXX_X,X_______,
  ______XX,_XXXXX_X,X_______,
  ______XX,_XXXX__X,X_______,
  ______X_,___XX__X,X_______,
  ______X_,___XX__X,X_______,
  ________,___X_XXX,X_______,
  ________,___X__XX,X_______,
  ________,_______X,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_8C22[ 72] = { /* code 8C22 */
  ________,__X_____,________,
  ________,__XXX___,________,
  _____XX_,__XX____,X_______,
  _____XXX,_XXXX___,_X______,
  _____XXX,_X___X__,_X______,
  ____XX_X,XXXX_X__,_X______,
  __XX____,XXXX_X__,_XX_____,
  _X___X__,X____X__,XXXX____,
  _X_XXX__,XXXXX_XX,XX______,
  _XXXXX__,XX__XXX_,_X______,
  __XXXX__,X__XX___,_X______,
  ____XXX_,_XXXX_X_,_X______,
  ____X_XX,X_XXX_XX,_X______,
  ____XX__,_XX_XX__,_X______,
  ____XX__,XX__X_X_,_X______,
  ____XX_X,X___X_X_,_X______,
  ____XX_X,_X__X__X,_X______,
  ________,__XXX__X,XX______,
  ________,___XX___,XX______,
  ________,____X___,_X______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_8E0F[ 72] = { /* code 8E0F */
  ________,________,________,
  ________,_____X__,________,
  ________,____XXXX,________,
  ______XX,XX____XX,_XX_____,
  _____XXX,XX____XX,X_X_____,
  ___XXXXX,XX____XX,_XX_____,
  ____X__X,XXXX__X_,XX______,
  ____XXXX,X_XX_XX_,XXXX____,
  ____XXXX,XX_XX_X_,XXXX____,
  ____XXX_,_XXXX_X_,_XX_____,
  _____X__,X_XX_XXX,X_______,
  ____X__X,X_X_X_XX,X_______,
  ____X_XX,____XX__,XX______,
  ___XX_X_,X___X_X_,XX______,
  ___X____,X___XXXX,XX______,
  ___X_XXX,X___XX__,XX______,
  ____XXX_,____XXX_,XX______,
  _____X__,_____XXX,XX______,
  ________,_____X_X,X_______,
  ________,________,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_8E29[ 72] = { /* code 8E29 */
  ________,________,________,
  ________,______XX,________,
  ________,______XX,X_______,
  _______X,X____XXX,X_______,
  _____XXX,XX_XXX_X,________,
  ___XX___,XXX___X_,X_______,
  ____XX_X,X___XXX_,XX______,
  ____XXXX,X_XX__XX,X_______,
  ____XXXX,X_XX_XXX,________,
  ____XXXX,__XXXXXX,XX______,
  ____X_X_,___XXXXX,XX______,
  _____X_X,XXXXXXX_,________,
  ____XXXX,_XXXX_X_,________,
  ____X__X,___XXXX_,________,
  ___XX___,X_XX__XX,X_______,
  ___X____,XXX___X_,XXXX____,
  ___XXXXX,_XX___X_,__XXX___,
  ____XX__,___XXXX_,____X___,
  ________,____XXX_,________,
  ________,_____XX_,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_900F[ 72] = { /* code 900F */
  ________,_____X__,________,
  ________,____XXX_,________,
  ________,_XXXXXX_,________,
  ________,_XXXXX__,________,
  ________,_____XX_,________,
  ____XX__,___XXXX_,________,
  _____XX_,_XXXXX_X,________,
  ____XXX_,XX__XXXX,X_______,
  ___X___X,XXXXXXXX,________,
  __X_____,XXXX_X__,________,
  __XXX___,XXXXXXX_,________,
  ____XX__,X__XXXX_,________,
  ____X___,__XXX_XX,________,
  ____X___,_XXX__XX,X_______,
  _____X__,_XXX____,X_______,
  _____X__,_XXX___X,X_______,
  ___XXXXX,XXXX__XX,________,
  ________,__XXXXXX,XXXXX___,
  ________,______XX,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_904D[ 72] = { /* code 904D */
  ________,________,________,
  ________,____XXXX,________,
  ________,____XXXX,________,
  ________,____XX__,________,
  ________,__XX_XXX,X_______,
  ____X___,__XXXX_X,XX______,
  _____XXX,__X___XX,X_______,
  _____XXX,__X_XXXX,X_______,
  ____X___,__XX____,________,
  ____X___,_X____XX,XX______,
  ____XX__,_X___X_X,_XX_____,
  _____X__,_XX__XXX,_XX_____,
  _____X__,_XXXXXXX,XXX_____,
  _____XX_,X_XXXXX_,_X______,
  ______XX,__X__XX_,_X______,
  ____XXXX,X_X__XXX,XX______,
  _____XXX,XXXXXX__,XX______,
  ________,____XXXX,XXXXXXX_,
  ________,_______X,XXXXXX__,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

/* Start of unicode area <Halfwidth and Fullwidth Forms> */
GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai24_FF0C[ 72] = { /* code FF0C, FULLWIDTH COMMA */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _____X__,________,________,
  _____XX_,________,________,
  ____XX__,________,________,
  _____X__,________,________,
  ____X___,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontxingkai24_CharInfo[38] = {
   {   6,   6,  1, acGUI_Fontxingkai24_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_Fontxingkai24_0021 } /* code 0021 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_4E00 } /* code 4E00 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_4F60 } /* code 4F60 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_535A } /* code 535A */
  ,{  23,  23,  3, acGUI_Fontxingkai24_548C } /* code 548C */
  ,{  23,  23,  3, acGUI_Fontxingkai24_5988 } /* code 5988 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_5BF8 } /* code 5BF8 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_5BF9 } /* code 5BF9 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_5D14 } /* code 5D14 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_5E08 } /* code 5E08 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_5FC3 } /* code 5FC3 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_6069 } /* code 6069 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_60A8 } /* code 60A8 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_610F } /* code 610F */
  ,{  23,  23,  3, acGUI_Fontxingkai24_656C } /* code 656C */
  ,{  23,  23,  3, acGUI_Fontxingkai24_662F } /* code 662F */
  ,{  23,  23,  3, acGUI_Fontxingkai24_6653 } /* code 6653 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_674E } /* code 674E */
  ,{  23,  23,  3, acGUI_Fontxingkai24_6885 } /* code 6885 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_6BCF } /* code 6BCF */
  ,{  23,  23,  3, acGUI_Fontxingkai24_6DF1 } /* code 6DF1 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_6EE1 } /* code 6EE1 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_7075 } /* code 7075 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_7231 } /* code 7231 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_7238 } /* code 7238 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_7530 } /* code 7530 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_7684 } /* code 7684 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_7EAA } /* code 7EAA */
  ,{  23,  23,  3, acGUI_Fontxingkai24_8001 } /* code 8001 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_83B9 } /* code 83B9 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_89D2 } /* code 89D2 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_8C22 } /* code 8C22 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_8E0F } /* code 8E0F */
  ,{  23,  23,  3, acGUI_Fontxingkai24_8E29 } /* code 8E29 */
  ,{  23,  23,  3, acGUI_Fontxingkai24_900F } /* code 900F */
  ,{  23,  23,  3, acGUI_Fontxingkai24_904D } /* code 904D */
  ,{  23,  23,  3, acGUI_Fontxingkai24_FF0C } /* code FF0C */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop36 = {
   0xFF0C /* first character */
  ,0xFF0C /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 37] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop35 = {
   0x904D /* first character */
  ,0x904D /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 36] /* address of first character */
  ,&GUI_Fontxingkai24_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop34 = {
   0x900F /* first character */
  ,0x900F /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 35] /* address of first character */
  ,&GUI_Fontxingkai24_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop33 = {
   0x8E29 /* first character */
  ,0x8E29 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 34] /* address of first character */
  ,&GUI_Fontxingkai24_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop32 = {
   0x8E0F /* first character */
  ,0x8E0F /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 33] /* address of first character */
  ,&GUI_Fontxingkai24_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop31 = {
   0x8C22 /* first character */
  ,0x8C22 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 32] /* address of first character */
  ,&GUI_Fontxingkai24_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop30 = {
   0x89D2 /* first character */
  ,0x89D2 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 31] /* address of first character */
  ,&GUI_Fontxingkai24_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop29 = {
   0x83B9 /* first character */
  ,0x83B9 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontxingkai24_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop28 = {
   0x8001 /* first character */
  ,0x8001 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontxingkai24_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop27 = {
   0x7EAA /* first character */
  ,0x7EAA /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontxingkai24_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop26 = {
   0x7684 /* first character */
  ,0x7684 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontxingkai24_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop25 = {
   0x7530 /* first character */
  ,0x7530 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontxingkai24_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop24 = {
   0x7238 /* first character */
  ,0x7238 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontxingkai24_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop23 = {
   0x7231 /* first character */
  ,0x7231 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontxingkai24_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop22 = {
   0x7075 /* first character */
  ,0x7075 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 23] /* address of first character */
  ,&GUI_Fontxingkai24_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop21 = {
   0x6EE1 /* first character */
  ,0x6EE1 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontxingkai24_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop20 = {
   0x6DF1 /* first character */
  ,0x6DF1 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontxingkai24_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop19 = {
   0x6BCF /* first character */
  ,0x6BCF /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontxingkai24_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop18 = {
   0x6885 /* first character */
  ,0x6885 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 19] /* address of first character */
  ,&GUI_Fontxingkai24_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop17 = {
   0x674E /* first character */
  ,0x674E /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontxingkai24_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop16 = {
   0x6653 /* first character */
  ,0x6653 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontxingkai24_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop15 = {
   0x662F /* first character */
  ,0x662F /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontxingkai24_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop14 = {
   0x656C /* first character */
  ,0x656C /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontxingkai24_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop13 = {
   0x610F /* first character */
  ,0x610F /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontxingkai24_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop12 = {
   0x60A8 /* first character */
  ,0x60A8 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontxingkai24_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop11 = {
   0x6069 /* first character */
  ,0x6069 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontxingkai24_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop10 = {
   0x5FC3 /* first character */
  ,0x5FC3 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontxingkai24_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop9 = {
   0x5E08 /* first character */
  ,0x5E08 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontxingkai24_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop8 = {
   0x5D14 /* first character */
  ,0x5D14 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[  9] /* address of first character */
  ,&GUI_Fontxingkai24_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop7 = {
   0x5BF8 /* first character */
  ,0x5BF9 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[  7] /* address of first character */
  ,&GUI_Fontxingkai24_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop6 = {
   0x5988 /* first character */
  ,0x5988 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[  6] /* address of first character */
  ,&GUI_Fontxingkai24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop5 = {
   0x548C /* first character */
  ,0x548C /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[  5] /* address of first character */
  ,&GUI_Fontxingkai24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop4 = {
   0x535A /* first character */
  ,0x535A /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[  4] /* address of first character */
  ,&GUI_Fontxingkai24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop3 = {
   0x4F60 /* first character */
  ,0x4F60 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[  3] /* address of first character */
  ,&GUI_Fontxingkai24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop2 = {
   0x4E00 /* first character */
  ,0x4E00 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[  2] /* address of first character */
  ,&GUI_Fontxingkai24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxingkai24_Prop1 = {
   0x0020 /* first character */
  ,0x0021 /* last character  */
  ,&GUI_Fontxingkai24_CharInfo[  0] /* address of first character */
  ,&GUI_Fontxingkai24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontxingkai24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontxingkai24_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

