/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 3064.c                                                *
* Font:        »ªÎÄçúçê                                              *
* Height:      70                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  70                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\1.txt            *
*                                                                    *
**********************************************************************
*/

#include "CUIGUI_FONT.H"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font3064;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font3064_6280[630] = { /* code 6280 */
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,____XXXX,XXXXXX__,________,________,XXXXXXXX,XX______,________,________,
  ________,___XXXXX,XXXXXXX_,________,______XX,XXXXXXXX,XXXX____,________,________,
  ________,__XXXXXX,XXXXXXXX,________,_____XXX,XXXXXXXX,XXXX____,________,________,
  ________,__XXXXXX,XXXXXXXX,________,_____XXX,XXXXXXXX,XXXXX___,________,________,
  ________,__XXXXXX,XXXXXXXX,________,_____XXX,XXXXXXXX,XXXXX___,________,________,
  ________,__XXXXXX,XXXXXXXX,________,_____XXX,XXXXXXXX,XXXXX___,________,________,
  ________,__XXXXXX,XXXXXXXX,________,_____XXX,XXXXXXXX,XXXXX___,________,________,
  ________,__XXXXXX,XXXXXXXX,________,_____XXX,XXXXXXXX,XXXXX___,________,________,
  ________,__XXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXXXXXX,___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,_XXXXXXX,XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XX_XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXX_XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,_____XXX,XXXXXXXX,XXXX____,________,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXX____,_____XXX,XXXXXXXX,XXXX____,________,________,
  ________,_XXXXXXX,XXXXXXXX,________,_____XXX,XXXXXXXX,XXXXX___,________,________,
  ________,__XXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,__XXXXXX,XXXXXXXX,____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX__X,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XX____XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,_______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  _____XXX,XXXXXXXX,XXXXXXXX,_______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,__XXXXXX,XXXXXXXX,________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  ________,__XXXXXX,XXXXXXXX,________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,__XXXXXX,XXXXXXXX,________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,__XXXXXX,XXXXXXXX,_______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,_XXXXXXX,XXXXXXXX,____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ______XX,XXXXXXXX,XXXXXXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX___X,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXX_,XXXXXXXX,XXXXXXXX,X_______,__XXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXX_,XXXXXXXX,XXXXXXX_,________,____XXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XXXXXXX_,_XXXXXXX,XXXXX___,________,______XX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XXXXX___,___XXXXX,XX______,________,________,XXXXXXXX,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font3064_63A2[630] = { /* code 63A2 */
  ________,________,________,________,________,________,________,________,________,
  ________,______XX,XX______,________,________,________,________,________,________,
  ________,___XXXXX,XXXXXX__,________,________,________,________,________,________,
  ________,__XXXXXX,XXXXXX__,___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,_XXXXXXX,XXXXXXX_,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,_XXXXXXX,XXXXXXX_,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX__XX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX__XX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX___X,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X__XXXXX,XXXXXXXX,XXXX___X,XXXXXXXX,XXXX_XXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_XXXXXX,XXXXXXXX,XXX_____,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,XXXXXXXX,XXXXX___,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,_XXXXXXX,XXXXX___,________,
  ________,_XXXXXXX,XXXXXXX_,_XXXXXXX,XXXXXXXX,XX______,_XXXXXXX,XXXXX___,________,
  ________,_XXXXXXX,XXXXXXX_,_XXXXXXX,XXXXXXXX,X_______,__XXXXXX,XXXX____,________,
  ________,_XXXXXXX,XXXXXXX_,_XXXXXXX,XXXXXXX_,_XXXXXXX,__XXXXXX,XXX_____,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX__XXXX,X_______,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX_XX,XXXXXXXX,XXX_____,________,________,
  ________,_XXXXXXX,XXXXXXXX,XX_XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,________,
  ________,_XXXXXXX,XXXXXXXX,XX______,_____XXX,XXXXXXXX,XXXX____,________,________,
  _____XXX,XXXXXXXX,XXXXXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_____XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  ______XX,XXXXXXXX,XXXXXXXX,XX__XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  ________,_XXXXXXX,XXXXXXXX,XX_XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ________,_XXXXXXX,XXXXXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ____XXXX,XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX_XXX,XXXXXXXX,XXX_XXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX___XXX,XXXXXXXX,XXX__XXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXX____X,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXX__,XXXXXX__,_____XXX,XXXXXXXX,XXX_____,_XXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXX__,________,______XX,XXXXXXXX,XXX_____,________,________,
  _____XXX,XXXXXXXX,XXXXXX__,________,______XX,XXXXXXXX,XX______,________,________,
  ______XX,XXXXXXXX,XXXX____,________,_______X,XXXXXXXX,X_______,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font3064_79D1[630] = { /* code 79D1 */
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,XXXXXXX_,________,________,_XXXXXXX,XXXX____,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,XXXXXXXX,XXXXXX__,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,_______X,XXXXXXXX,XXXXXX__,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXXXX,XX_____X,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_XXXXXX,XXXX___X,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX__X,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_XXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _______X,XXXXXXXX,XXXXXXXX,XXX_____,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX____XX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_XXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_XXX_,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,XXXXXXXX,XXXXX___,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXX_,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXX___,______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXX_XXX,XXX____X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXX_XXXX,XXXX____,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXX___,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXX__,___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXX_,____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,______XX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_______X,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,_XXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,______XX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,____XXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX_XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXX_,XXXXX_XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX_XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _______X,XXXXXXXX,XXXXXXXX,XXX_XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX__XXX,XXXXXXXX,XX____XX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,________,______XX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,________,______XX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,________,______XX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,________,______XX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,________,______XX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,________,______XX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,________,______XX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,________,_______X,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,________,_______X,XXXXXXXX,XXXXXXX_,________,
  ________,____XXXX,XXXXXXXX,XXX_____,________,_______X,XXXXXXXX,XXXXXXX_,________,
  ________,____XXXX,XXXXXXXX,XX______,________,_______X,XXXXXXXX,XXXXXX__,________,
  ________,_____XXX,XXXXXXXX,X_______,________,________,_XXXXXXX,XXXXX___,________,
  ________,________,_XXXX___,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font3064_957F[630] = { /* code 957F */
  ________,________,________,________,________,________,________,________,________,
  ________,______XX,XXXX____,________,________,________,________,________,________,
  ________,___XXXXX,XXXXXXX_,________,________,_______X,XXXXX___,________,________,
  ________,__XXXXXX,XXXXXXXX,________,________,_____XXX,XXXXXX__,________,________,
  ________,__XXXXXX,XXXXXXXX,________,________,____XXXX,XXXXXXX_,________,________,
  ________,__XXXXXX,XXXXXXXX,________,________,__XXXXXX,XXXXXXXX,________,________,
  ________,__XXXXXX,XXXXXXXX,________,________,_XXXXXXX,XXXXXXXX,X_______,________,
  ________,__XXXXXX,XXXXXXXX,________,________,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,__XXXXXX,XXXXXXXX,________,_______X,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,__XXXXXX,XXXXXXXX,________,_____XXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,__XXXXXX,XXXXXXXX,________,____XXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,__XXXXXX,XXXXXXXX,________,___XXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,__XXXXXX,XXXXXXXX,________,_XXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,__XXXXXX,XXXXXXXX,________,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,__XXXXXX,XXXXXXXX,_______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,
  ________,__XXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,
  ________,__XXXXXX,XXXXXXXX,____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,________,
  ________,__XXXXXX,XXXXXXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,________,
  ________,__XXXXXX,XXXXXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,__XXXXXX,XXXXXXXX,____XXXX,XXXXXXXX,XXXX____,________,________,________,
  ________,__XXXXXX,XXXXXXXX,____XXXX,XXXXXXXX,XXXXX___,________,________,________,
  ________,__XXXXXX,XXXXXXXX,____XXXX,XXXXXXXX,XXXXXX__,________,________,________,
  ________,__XXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXXXX_,________,________,________,
  ________,__XXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXXXX_,________,________,________,
  ________,__XXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXXXXX,________,________,________,
  ________,__XXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,XXXXXXXX,X_______,________,________,
  ________,__XXXXXX,XXXXXXXX,______XX,XXXXXXXX,XXXXXXXX,XX______,________,________,
  ________,__XXXXXX,XXXXXXXX,______XX,XXXXXXXX,XXXXXXXX,XXX_____,________,________,
  ________,__XXXXXX,XXXXXXXX,_______X,XXXXXXXX,XXXXXXXX,XXXX____,________,________,
  ________,__XXXXXX,XXXXXXXX,________,_XXXXXXX,XXXXXXXX,XXXXXX__,________,________,
  ________,__XXXXXX,XXXXXXXX,________,___XXXXX,XXXXXXXX,XXXXXXX_,________,________,
  ________,__XXXXXX,XXXXXXXX,__XXXXXX,XXX_XXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX_XX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX_XX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,_XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,__XXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,___XXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,_____XXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,______XX,XXXXXXXX,XXXXXX__,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXX_,________,________,XXXXXXXX,XXXXXX__,________,
  ________,___XXXXX,XXXXXXXX,XXXX____,________,________,_XXXXXXX,XXXXX___,________,
  ________,____XXXX,XXXXXXXX,________,________,________,___XXXXX,XXXX____,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________,
  ________,________,________,________,________,________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font3064_CharInfo[4] = {
   {  69,  69,  9, acGUI_Font3064_6280 } /* code 6280 */
  ,{  69,  69,  9, acGUI_Font3064_63A2 } /* code 63A2 */
  ,{  69,  69,  9, acGUI_Font3064_79D1 } /* code 79D1 */
  ,{  69,  69,  9, acGUI_Font3064_957F } /* code 957F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font3064_Prop4 = {
   0x957F /* first character */
  ,0x957F /* last character  */
  ,&GUI_Font3064_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font3064_Prop3 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_Font3064_CharInfo[  2] /* address of first character */
  ,&GUI_Font3064_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font3064_Prop2 = {
   0x63A2 /* first character */
  ,0x63A2 /* last character  */
  ,&GUI_Font3064_CharInfo[  1] /* address of first character */
  ,&GUI_Font3064_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font3064_Prop1 = {
   0x6280 /* first character */
  ,0x6280 /* last character  */
  ,&GUI_Font3064_CharInfo[  0] /* address of first character */
  ,&GUI_Font3064_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font3064 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,70 /* height of font  */
  ,70 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font3064_Prop1}
  ,55 /* Baseline */
  ,35 /* Height of lowercase characters */
  ,48 /* Height of capital characters */
};

