/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: songti24.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Read pattern file: D:\MyWork\CUIGUI\font\1.txt                     *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\MyWork\CUIGUI\font\1.txt                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_6211[ 72] = { /* code 6211 */
  ________,________,________,
  ________,_____X__,________,
  ________,_XX__XX_,________,
  _____XXX,XX___X__,_XX_____,
  __XXX__X,_____X__,__XX____,
  _______X,_____X__,___X____,
  _______X,_____X__,___X____,
  _______X,_____X__,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  _______X,_____X__,________,
  _______X,_____XX_,________,
  _______X,_____XX_,__XX____,
  _______X,__XX_XX_,__X_____,
  _______X,XX____X_,_X______,
  ____XXXX,______X_,XX______,
  _XXXX__X,______XX,X_______,
  __X____X,______XX,________,
  _______X,_____XXX,________,
  _______X,____XX_X,X____X__,
  _______X,___X____,XX___X__,
  _______X,XXX_____,_XXX_X__,
  ____XXXX,________,___XXX__,
  ______X_,________,_____XX_,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsongti24_CharInfo[1] = {
   {  24,  24,  3, acGUI_Fontsongti24_6211 } /* code 6211 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti24_Prop1 = {
   0x6211 /* first character */
  ,0x6211 /* last character  */
  ,&GUI_Fontsongti24_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsongti24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

